### PR TITLE
Fix for rad init UI issue on a small terminal

### LINKED ISSUE #6492: rad init UI can be cut off on a small terminal
### Steps to reproduce (required)

Make your terminal pretty small.

Run `rad init`

### Observed behavior (required)

This is what I see:

image

### Desired behavior (required)

`rad init` UI works

### Workaround (optional)

Resize terminal

[AB#9829](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/9829)

### PR DESCRIPTION
**Pull request by vishwahiremat**
# Description

- Removed hard coded values for width and height for list model.
- Dynamically change the width or height of the list model depending on the terminal dimensions.

## Type of change

- This pull request fixes a bug in Radius and has an approved issue (issue link required).

Fixes: https://github.com/radius-project/radius/issues/6492

## Contributor checklist
Please verify that the PR meets the following requirements, where applicable:

- [ ] An overview of proposed schema changes is included in a linked GitHub issue.
- [ ] A design document PR is created in the [design-notes repository](https://github.com/radius-project/design-notes/), if new APIs are being introduced.
- [ ] If applicable, design document has been reviewed and approved by Radius maintainers/approvers.
- [ ] A PR for the [samples repository](https://github.com/radius-project/samples) is created, if existing samples are affected by the changes in this PR.
- [ ] A PR for the [documentation repository](https://github.com/radius-project/docs) is created, if the changes in this PR affect the documentation or any user facing updates are made.
- [ ] A PR for the [recipes repository](https://github.com/radius-project/recipes) is created, if existing recipes are affected by the changes in this PR.

### CODE REVIEW

File: pkg/cli/prompt/list/list.go [hunk 1]
```diff
@@ -26,9 +26,9 @@ import (
 	"github.com/charmbracelet/x/ansi"
 )
 
-const listHeight = 14
+// const listHeight = 8
```
Comment (sk593) [inline pkg/cli/prompt/list/list.go:29]: Should these be deleted

**Review by sk593 — DISMISSED** [review]

File: pkg/cli/prompt/list/list.go [hunk 2]
```diff
@@ -92,7 +88,7 @@ func NewListModel(choices []string, promptMsg string) ListModel {
 		items[i] = item(choice)
 	}
 
-	l := list.New(items, itemHandler{}, defaultWidth, listHeight)
+	l := list.New(items, itemHandler{}, 0, 0)
```
Comment (kachawla) [inline pkg/cli/prompt/list/list.go:91]: nit: let's add a comment here about 0 values.

File: pkg/cli/prompt/list/list.go [hunk 3]
```diff
@@ -134,6 +130,7 @@ func (m ListModel) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
 	switch msg := msg.(type) {
 	case tea.WindowSizeMsg:
 		m.width = msg.Width
+		m.List.SetSize(msg.Width, msg.Height-((3*msg.Height)/4))
```
Comment (kachawla) [inline pkg/cli/prompt/list/list.go:133]: same here, let's add a comment for quick description why we are doing this since it might not be obvious from the code.

**Review by kachawla — COMMENTED** [review]
Thanks for fixing, looks good apart from a minor comment.

File: pkg/cli/prompt/list/list.go (hunk 2 above)
Comment (vishwahiremat) [reply pkg/cli/prompt/list/list.go:92]: added comments

File: pkg/cli/prompt/list/list.go [hunk 4]
```diff
@@ -134,6 +131,9 @@ func (m ListModel) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
 	switch msg := msg.(type) {
 	case tea.WindowSizeMsg:
 		m.width = msg.Width
+		// setting the width and height of the list model as terminal dimensions changes.
+		// setting the height to 25% of the height of the terminal height.
```
Comment (kachawla) [inline pkg/cli/prompt/list/list.go:135]: why 25% specifically?

**Review by kachawla — APPROVED** [review]

File: pkg/cli/prompt/list/list.go (hunk 4 above)
Comment (vishwahiremat) [reply pkg/cli/prompt/list/list.go:135]: we want to change the dimension of the list model as terminal dimensions changes, and I am setting it to 25% because i figured its close to the existing size of the list model on a full terminal window.
