### PR TITLE
rad deploy should be able work with both rad core and app core environments

### LINKED ISSUE #10895: rad deploy fails when using Radius.Core/environments
### Steps to reproduce

1) create a Radius.Core/environments using `rad env create  test --preview`
2) update the environment with recipepack `rad env update test --recipe-packs computeRecipePack --kubernetes-namespace <ns>`
3) rad deploy app.bicep

app.bicep
```
extension testresources
extension radius

param environment string 
@description('PostgreSQL password')
@secure()
param password string = newGuid()


resource udtpg 'Test.Resources/postgres@2025-01-01-preview' = {
  name: 'postgres-resource'
  location: 'global'
  properties: {
    environment: environment
    password: password
  }
}

```

### Observed behavior

```
Building app.bicep...
The template "app.bicep" could not be deployed because of the following errors:

  - The template requires an environment. Use --environment to specify the environment name.
```

### Desired behavior

- should not throw an error, instead it should pick the current radius environment and automaticlly pass it as a param.

### Workaround

explicilty pass environment as a parameter using 
```
rad deploy app.bicep --parameters environment=<fully qualifies resource ID of the environment>
```

### rad Version

CLI Version Information:
RELEASE   VERSION                         BICEP     COMMIT
edge      v0.50.0-rc4-147-gac0f39c-dirty  0.38.33   ac0f39c22efd2490a8452e5a8d235ae333ffcf66

Control Plane Information:
STATUS     VERSION
Installed  0.52.0

### Operating system

_No response_

### Additional context

_No response_

[AB#17855](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/17855)

### PR DESCRIPTION
**Pull request by nithyatsu**
# Description

- Dual-provider environment lookup - check both Applications.Core and Radius.Core providers when resolving environment names, automatically selecting the correct provider setting logic based on which one contains the environment

- Conflict detection: Returns clear error message when an environment with the same name exists in both Applications.Core and Radius.Core, prompting users to specify the full resource ID to disambiguate

- Refactored provider configuration: Unified configureProviders() method handles both v20231001preview (Applications.Core) and v20250801preview (Radius.Core) API versions, 

- Application ID provider inferred correctly based on the environment in use.

Below cases should now work:

rad deploy /Users/nithya/rp/app.bicep -e /planes/radius/local/resourceGroups/default/providers/Applications.Core/environments/radcoreenv

rad deploy /Users/nithya/rp/app.bicep -e /planes/radius/local/resourceGroups/default/providers/Radius.Core/environments/radcoreenv

rad deploy /Users/nithya/rp/app.bicep -e radcoreenv (returns conflict error)

vi ~/rp/app.bicep  # set workspace env to an application core env
rad deploy /Users/nithya/rp/app.bicep 

vi ~/.rad/config.yaml  # set workspace env to a radius core env
rad deploy /Users/nithya/rp/app.bicep 

## Type of change

Fixes: #10895 

## Contributor checklist
Please verify that the PR meets the following requirements, where applicable:

- An overview of proposed schema changes is included in a linked GitHub issue.
    - [ ] Yes 
    - [x] Not applicable 
- A design document PR is created in the [design-notes repository](https://github.com/radius-project/design-notes/), if new APIs are being introduced.
    - [ ] Yes 
    - [x] Not applicable 
- The design document has been reviewed and approved by Radius maintainers/approvers.
    - [ ] Yes 
    - [x] Not applicable 
- A PR for the [samples repository](https://github.com/radius-project/samples) is created, if existing samples are affected by the changes in this PR.
    - [ ] Yes 
    - [x] Not applicable 
- A PR for the [documentation repository](https://github.com/radius-project/docs) is created, if the changes in this PR affect the documentation or any user facing updates are made.
    - [ ] Yes 
    - [x] Not applicable 
- A PR for the [recipes repository](https://github.com/radius-project/recipes) is created, if existing recipes are affected by the changes in this PR.
    - [ ] Yes 
    - [x] Not applicable

### CODE REVIEW

File: pkg/cli/cmd/deploy/deploy.go [hunk 1]
```diff
@@ -35,11 +36,19 @@ import (
...
 	"github.com/radius-project/radius/pkg/to"
+	"github.com/radius-project/radius/pkg/ucp/resources"
 	"github.com/spf13/cobra"
 	"golang.org/x/exp/maps"
 )
 
+const (
+	appCoreProviderName    = "Applications.Core"
+	radiusCoreProviderName = "Radius.Core"
+)
```
Comment (ytimocin) [inline pkg/cli/cmd/deploy/deploy.go:49]: Why don't we have these two in a more global package that can be used from all around the codebase?

File: pkg/cli/cmd/deploy/deploy.go [hunk 2]
```diff
@@ -35,11 +36,19 @@ import (
 	"github.com/radius-project/radius/pkg/cli/output"
 	"github.com/radius-project/radius/pkg/cli/workspaces"
 	"github.com/radius-project/radius/pkg/corerp/api/v20231001preview"
+	"github.com/radius-project/radius/pkg/corerp/api/v20250801preview"
+	corerpv20250801 "github.com/radius-project/radius/pkg/corerp/api/v20250801preview"
```
Comment (ytimocin) [inline pkg/cli/cmd/deploy/deploy.go]: These 2 are the same.

File: pkg/cli/cmd/deploy/deploy.go [hunk 3]
```diff
@@ -273,30 +263,40 @@ func (r *Runner) Run(ctx context.Context) error {
...
-			if err != nil {
-				return err
+		// Environment validation has already happened, so only create application if we have an environment
+		if r.Workspace.Environment != "" {
+			if _, err := isApplicationsCoreProvider(r.Providers.Radius.EnvironmentID); err == nil {
+				client, err := r.ConnectionFactory.CreateApplicationsManagementClient(ctx, *r.Workspace)
+				if err != nil {
+					return err
+				}
+				err = client.CreateApplicationIfNotFound(ctx, r.ApplicationName, &v20231001preview.ApplicationResource{
```
Comment (ytimocin) [inline pkg/cli/cmd/deploy/deploy.go:290]: nit: extra line before this for readability

File: pkg/cli/cmd/deploy/deploy.go [hunk 4]
```diff
@@ -397,3 +397,271 @@ func (r *Runner) reportMissingParameters(template map[string]any) error {
 
 	return clierrors.Message("The template %q could not be deployed because of the following errors:\n\n%v", r.FilePath, strings.Join(details, "\n"))
 }
+
+// determineEnvironmentProvider determines which provider to use based on the environment ID
+func isApplicationsCoreProvider(id string) (bool, error) {
```
Comment (ytimocin) [inline pkg/cli/cmd/deploy/deploy.go:420]: This should also live in a more global package.

**Review by ytimocin — CHANGES_REQUESTED** [review]

File: pkg/cli/cmd/deploy/deploy.go (hunk 1 above)
Comment (nithyatsu) [reply pkg/cli/cmd/deploy/deploy.go:49]: I added them for just thse commands. But mainly, I think the work has wrapped up, and early next year we will have to work on removing applications.core namespace. I will move these to global package if I have one more task that needs them in future, is that OK?

File: pkg/cli/cmd/deploy/deploy.go [hunk 5]
```diff
@@ -273,30 +263,40 @@ func (r *Runner) Run(ctx context.Context) error {
...
-				Location: to.Ptr(v1.LocationGlobal),
-				Properties: &v20231001preview.ApplicationProperties{
-					Environment: &r.Workspace.Environment,
-				},
-			})
-			if err != nil {
-				return err
+		// Environment validation has already happened, so only create application if we have an environment
+		if r.Workspace.Environment != "" {
+			if _, err := isApplicationsCoreProvider(r.Providers.Radius.EnvironmentID); err == nil {
```
[the remark this answers is not in the document]
Comment (nithyatsu) [reply pkg/cli/cmd/deploy/deploy.go:285]: This is because FetchEnvironment handles it in detail.

File: pkg/cli/cmd/deploy/deploy.go (hunk 4 above)
Comment (nithyatsu) [reply pkg/cli/cmd/deploy/deploy.go:420]: Same reason as previous comment.

File: pkg/cli/cmd/deploy/deploy.go [hunk 6]
```diff
@@ -428,3 +414,289 @@ func (r *Runner) reportMissingParameters(template map[string]any) error {
...
+			radCoreEnvID = envNameOrID
+		}
+
+		if r.RadiusCoreClientFactory == nil {
+			clientFactory, err := cmd.InitializeRadiusCoreClientFactory(ctx, r.Workspace, r.Workspace.Scope)
+			if err != nil {
+				return nil, err
+			} else {
+				r.RadiusCoreClientFactory = clientFactory
+			}
```
Comment (kachawla) [inline pkg/cli/cmd/deploy/deploy.go]: `RadiusCoreClientFactory` is initialized again in `getRadiusCoreEnvironment`. Do we need to initialize it here in `FetchEnvironment`?

File: pkg/cli/cmd/deploy/deploy.go [hunk 7]
```diff
@@ -428,3 +414,289 @@ func (r *Runner) reportMissingParameters(template map[string]any) error {
...
+		}
+	} else {
+		return nil
+	}
+
+	switch e := env.(type) {
+	case *v20231001preview.EnvironmentResource:
+		if e != nil && e.ID != nil {
+			r.Providers.Radius.EnvironmentID = *e.ID
```
Comment (kachawla) [inline pkg/cli/cmd/deploy/deploy.go]: `if e != nil && e.ID != nil {
			r.Providers.Radius.EnvironmentID = *e.ID`
is repeated in `setupEnvironmentID` which we are calling in next line. Do we need to set it twice?

File: pkg/cli/cmd/deploy/deploy.go [hunk 8]
```diff
@@ -428,3 +414,289 @@ func (r *Runner) reportMissingParameters(template map[string]any) error {
 
 	return clierrors.Message("The template %q could not be deployed because of the following errors:\n\n%v", r.FilePath, strings.Join(details, "\n"))
 }
+
+// determineEnvironmentProvider determines which provider to use based on the environment ID
```
Comment (kachawla) [inline pkg/cli/cmd/deploy/deploy.go]: nit: the comment needs to be updated

**Review by ytimocin — DISMISSED** [review]
I'd also get the thumbs up from @kachawla

File: pkg/cli/cmd/deploy/deploy.go (hunk 6 above)
Comment (nithyatsu) [reply pkg/cli/cmd/deploy/deploy.go]: I have removed the extra call.

File: pkg/cli/cmd/deploy/deploy.go (hunk 7 above)
Comment (nithyatsu) [reply pkg/cli/cmd/deploy/deploy.go]: removed redundant setting

**Review by kachawla — APPROVED** [review]
