### PR TITLE
Adding fix for publishing recipes to ECR

### LINKED ISSUE #7855: "rad bicep publish" Fails to Publish Bicep Files to ECR
### Steps to reproduce

1) login to acr
`aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin <account-name>.dkr.ecr.us-east-2.amazonaws.com`
2) publish bicep file to ECR
`rad bicep publish --file test/testrecipes/test-bicep-recipes/rabbitmq-recipe.bicep --target br:<account-name>.dkr.ecr.us-east-2.amazonaws.com/test-ecr:latest`

### Observed behavior

Throws `blob upload invalid` error

`
Failed to publish Bicep file "test/testrecipes/test-bicep-recipes/rabbitmq-recipe.bicep" to "<account-name>.dkr.ecr.us-east-2.amazonaws.com/test-ecr:1.0"
Something went wrong Cause: PUT "https://<account-name>.dkr.ecr.us-east-2.amazonaws.com/v2/test-private-ecr/blobs/uploads/47552bfb-e8f7-41ad-9c07-310446dc14?digest=sha256%3Ae3b0c44298fc1c149afbf4c8996fb927ae41e4649b934ca495991b7852b855": response status code 400: blob upload invalid: The upload with id '47552bfb-e8f7-41ad-9c07-314186dc14' in the repository with name 'test-ecr' in registry with id '<account-name>' cannot be completed because it does not have any parts.
`

### Desired behavior

Should be able to successfully upload bicep to ECR

### Workaround

_No response_

### rad Version

RELEASE   VERSION   BICEP     COMMIT
0.37.0    v0.37.0   0.29.47   b1a78222b715a29fd5d76858403bec8f686b732e

### Operating system

_No response_

### Additional context

_No response_

### Would you like to support us?

- [ ] Yes, I would like to support you

[AB#13092](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/13092)

### PR DESCRIPTION
**Pull request by vishwahiremat**
# Description

ECR thorws following  error when Data is nil, updating the data to a empty descriptor.
```
Something went wrong Cause: PUT "
https://<account-name>.dkr.ecr.us-east-2.amazonaws.com/v2/test-private-ecr/blobs/uploads/47552bfb-e8f7-41ad-9c07-310446dc14?digest=sha256%3Ae3b0c44298fc1c149afbf4c8996fb927ae41e4649b934ca495991b7852b855":
response status code 400: blob upload invalid: The upload with id '47552bfb-e8f7-41ad-9c07-314186dc14' in the repository with name 'test-ecr' in registry with id '<account-name>' cannot be completed because it does not have any parts.
```

## Type of change

- This pull request fixes a bug in Radius and has an approved issue (issue link required).
- This pull request adds or changes features of Radius and has an approved issue (issue link required).
- This pull request is a minor refactor, code cleanup, test improvement, or other maintenance task and doesn't change the functionality of Radius (issue link optional).

Fixes: https://github.com/radius-project/radius/issues/7855

### CODE REVIEW

**Review by lakshmimsft — DISMISSED** [review]

File: pkg/cli/cmd/bicep/publish/publish.go [hunk 1]
```diff
@@ -237,7 +237,7 @@ func (r *Runner) prepareSource(ctx context.Context) (*memory.Store, error) {
 	}
 
 	// Push config blob
-	configDesc, err := pushBlob(ctx, configMediaType, nil, src)
+	configDesc, err := pushBlob(ctx, configMediaType, []byte("{}"), src)
```
Comment (rynowak) [inline pkg/cli/cmd/bicep/publish/publish.go:240]: Can you add a comment here? I think it would be helpful to link the other issue where we found the root cause.

Comment (vishwahiremat) [reply pkg/cli/cmd/bicep/publish/publish.go:243]: Added a comment , also linked the issue for reference

Comment (rynowak) [reply pkg/cli/cmd/bicep/publish/publish.go:243]: Looks great! thanks.

**Review by rynowak — APPROVED** [review]
:shipit:

**Review by ytimocin — APPROVED** [review]
