### PR TITLE
Fix nil pointer dereference by setting Kind field in Azure credentials

### LINKED ISSUE #9452: invalid memory address or nil pointer dereference on `rad credential show azure`
### Steps to reproduce

```
$ rad credential register azure sp --client-id $AZURE_CLIENT_ID  --client-secret $AZURE_CLIENT_SECRET  --tenant-id $AZURE_TENANT_ID
Registering credential for "azure" cloud provider in Radius installation "Kubernetes (context=nimble)"...
Successfully registered credential for "azure" cloud provider. Tokens may take up to 30 seconds to refresh.
                                                                                                                                
$ rad credential list
Listing credentials for all cloud providers for Radius installation "Kubernetes (context=nimble)"...
PROVIDER  REGISTERED
azure     true

$ rad credential show azure
Showing credential for cloud provider "azure" for Radius installation "Kubernetes (context=nimble)"...
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x8 pc=0x1062544a4]

goroutine 1 [running]:
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End.deferwrap1()
        /home/runner/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.35.0/trace/span.go:467 +0x2c
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0x14000333680, {0x0, 0x0, 0x0?})
        /home/runner/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.35.0/trace/span.go:500 +0x99c
panic({0x106a4c880?, 0x1086953e0?})
        /opt/hostedtoolcache/go/1.24.1/x64/src/runtime/panic.go:792 +0x124
github.com/radius-project/radius/pkg/cli/cmd/credential/show.(*Runner).Run(0x14000836d20, {0x106f215d0, 0x140008478f0})
        /home/runner/work/radius/radius/pkg/cli/cmd/credential/show/show.go:134 +0x4c4
github.com/radius-project/radius/pkg/cli/cmd/credential/show.NewCommand.RunCommand.func2(0x1400084cf08, {0x14000467560?, 0x4?, 0x1062ef687?})
        /home/runner/work/radius/radius/pkg/cli/framework/framework.go:192 +0x7c
github.com/spf13/cobra.(*Command).execute(0x1400084cf08, {0x14000467530, 0x1, 0x1})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.9.1/command.go:1015 +0x828
github.com/spf13/cobra.(*Command).ExecuteC(0x1086ca4a0)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.9.1/command.go:1148 +0x350
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.9.1/command.go:1071
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.9.1/command.go:1064
github.com/radius-project/radius/cmd/rad/cmd.Execute()
        /home/runner/work/radius/radius/cmd/rad/cmd/root.go:169 +0x1d0
main.main()
        /home/runner/work/radius/radius/cmd/rad/main.go:26 +0x1c
```

### Observed behavior

_No response_

### Desired behavior

Show my service principal ID

### Workaround

_No response_

### rad Version

$ rad version              
CLI Version Information:
RELEASE   VERSION   BICEP     COMMIT
edge      75372b5   0.35.1    75372b5dc51b4b396eeda4b9d95af25d210054fa

Control Plane Information:
STATUS     VERSION
Installed  0.42.42-dev

### Operating system

_No response_

### Additional context

_No response_

### Would you like to support us?

- [ ] Yes, I would like to support you

[AB#15779](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/15779)

### PR DESCRIPTION
**Pull request by kachawla**
# Description

The `rad credential show azure` command panics with a nil pointer dereference when attempting to display Azure service principal credentials. The panic occurs because `AzureCredentialProperties.Kind` is dereferenced without being populated.

* Set the top-level Kind field in AzureCredentialProperties for both ServicePrincipal and WorkloadIdentity credential types.
* Added unit test coverage for WorkloadIdentity credential type.

## Type of change

- This pull request fixes a bug in Radius and has an approved issue (issue link required).

Fixes: https://github.com/radius-project/radius/issues/9452

## Contributor checklist
Please verify that the PR meets the following requirements, where applicable:

- An overview of proposed schema changes is included in a linked GitHub issue.
    - [ ] Yes 
    - [x] Not applicable 
- A design document PR is created in the [design-notes repository](https://github.com/radius-project/design-notes/), if new APIs are being introduced.
    - [ ] Yes 
    - [x] Not applicable 
- The design document has been reviewed and approved by Radius maintainers/approvers.
    - [ ] Yes 
    - [x] Not applicable 
- A PR for the [samples repository](https://github.com/radius-project/samples) is created, if existing samples are affected by the changes in this PR.
    - [ ] Yes 
    - [x] Not applicable 
- A PR for the [documentation repository](https://github.com/radius-project/docs) is created, if the changes in this PR affect the documentation or any user facing updates are made.
    - [ ] Yes 
    - [x] Not applicable 
- A PR for the [recipes repository](https://github.com/radius-project/recipes) is created, if existing recipes are affected by the changes in this PR.
    - [ ] Yes 
    - [x] Not applicable

### CODE REVIEW

**Review by willdavsmith — DISMISSED** [review]

**Review by kachawla — COMMENTED** [review]
Just fyi - I'm working on sending another PR to gracefully handle panics in CLI

File: pkg/cli/cmd/credential/show/show_test.go [hunk 1]
```diff
@@ -151,6 +151,53 @@ func Test_Run(t *testing.T) {
 			}
 			require.Equal(t, expected, outputSink.Writes)
 		})
+		t.Run("Azure WorkloadIdentity - Exists", func(t *testing.T) {
```
Comment (ytimocin) [inline pkg/cli/cmd/credential/show/show_test.go:155]: nit: extra line before this line

File: pkg/cli/cmd/credential/show/show_test.go [hunk 2]
```diff
@@ -151,6 +151,53 @@ func Test_Run(t *testing.T) {
...
+					Params: []any{"azure", "Kubernetes (context=my-context)"},
+				},
+				output.FormattedOutput{
+					Format:  "table",
+					Obj:     provider,
+					Options: credentialFormatOutput,
+				},
+			}
+			require.Equal(t, expected, outputSink.Writes)
+		})
```
Comment (ytimocin) [inline pkg/cli/cmd/credential/show/show_test.go:201]: nit: extra line after this line

File: pkg/cli/cmd/credential/show/show_test.go (hunk 1 above)
Comment (kachawla) [inline pkg/cli/cmd/credential/show/show_test.go:155]:
```suggestion
        
		t.Run("Azure WorkloadIdentity - Exists", func(t *testing.T) {
```

File: pkg/cli/cmd/credential/show/show_test.go [hunk 3]
```diff
@@ -151,6 +151,54 @@ func Test_Run(t *testing.T) {
...
```
Comment (kachawla) [inline pkg/cli/cmd/credential/show/show_test.go:201]:
```suggestion
		})
		
```

File: pkg/cli/cmd/credential/show/show_test.go (hunk 2 above)
Comment (kachawla) [reply pkg/cli/cmd/credential/show/show_test.go:201]: updated

**Review by ytimocin — APPROVED** [review]
LGTM
