### PR TITLE
Fix for flaky unit test

### LINKED ISSUE #7638: Flaky unit test `Test_AddProviders/valid_all_supported_providers`
### Steps to reproduce

This is happening on pipeline runs on the Terraform provider tests. It doesn't fail every time, but it seems like the first run of the test fails more often. For example, in this workflow the test failed twice before passing: https://github.com/radius-project/radius/actions/runs/9229268106 

### Observed behavior

```
=== Failed
=== FAIL: pkg/recipes/terraform/config Test_AddProviders/valid_all_supported_providers (0.00s)
    config.go:156: "ts"="2024-05-28 16:25:02.178601" "level"=0 "msg"="Updating module config with providers aliases"
    config.go:162: "ts"="2024-05-28 16:25:02.178741" "level"=0 "msg"="Update Terraform configuration with required providers"
    config.go:131: "ts"="2024-05-28 16:25:02.179185" "level"=0 "msg"="Writing Terraform JSON config to file: /tmp/Test_AddProvidersvalid_all_supported_providers3863394219/001/main.tf.json"
    config_test.go:641: 
        	Error Trace:	/home/runner/work/radius/radius/pkg/recipes/terraform/config/config_test.go:641
        	Error:      	Not equal: 
        	            	expected: "{\n  \"terraform\": {\n    \"backend\": {\n      \"kubernetes\": {\n        \"config_path\": \"/home/radius/.kube/config\",\n        \"namespace\": \"radius-system\",\n        \"secret_suffix\": \"test-secret-suffix\"\n      }\n    },\n    \"required_providers\": {\n      \"aws\": {},\n      \"azurerm\": {},\n      \"kubernetes\": {},\n      \"sql\": {}\n    }\n  },\n  \"provider\": {\n    \"aws\": [\n      {\n        \"region\": \"test-region\"\n      }\n    ],\n    \"azurerm\": [\n      {\n        \"features\": {},\n        \"subscription_id\": \"test-sub\"\n      }\n    ],\n    \"kubernetes\": [\n      {\n        \"config_path\": \"/home/radius/.kube/config\"\n      }\n    ]\n  },\n  \"module\": {\n    \"redis-azure\": {\n      \"redis_cache_name\": \"redis-test\",\n      \"resource_group_name\": \"test-rg\",\n      \"sku\": \"P\",\n      \"source\": \"Azure/redis/azurerm\",\n      \"version\": \"1.1.0\"\n    }\n  }\n}"
        	            	actual  : "{\n  \"terraform\": {\n    \"backend\": {\n      \"kubernetes\": {\n        \"config_path\": \"/home/radius/.kube/config\",\n        \"namespace\": \"radius-system\",\n        \"secret_suffix\": \"test-secret-suffix\"\n      }\n    },\n    \"required_providers\": {\n      \"aws\": {},\n      \"azurerm\": {},\n      \"kubernetes\": {},\n      \"sql\": {}\n    }\n  },\n  \"provider\": {\n    \"aws\": [\n      {\n        \"features\": {},\n        \"subscription_id\": \"test-sub\"\n      }\n    ],\n    \"azurerm\": [\n      {\n        \"config_path\": \"/home/radius/.kube/config\"\n      }\n    ],\n    \"kubernetes\": [\n      {\n        \"region\": \"test-region\"\n      }\n    ]\n  },\n  \"module\": {\n    \"redis-azure\": {\n      \"redis_cache_name\": \"redis-test\",\n      \"resource_group_name\": \"test-rg\",\n      \"sku\": \"P\",\n      \"source\": \"Azure/redis/azurerm\",\n      \"version\": \"1.1.0\"\n    }\n  }\n}"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -19,3 +19,4 @@
        	            	       {
        	            	-        "region": "test-region"
        	            	+        "features": {},
        	            	+        "subscription_id": "test-sub"
        	            	       }
        	            	@@ -24,4 +25,3 @@
        	            	       {
        	            	-        "features": {},
        	            	-        "subscription_id": "test-sub"
        	            	+        "config_path": "/home/radius/.kube/config"
        	            	       }
        	            	@@ -30,3 +30,3 @@
        	            	       {
        	            	-        "config_path": "/home/radius/.kube/config"
        	            	+        "region": "test-region"
        	            	       }
        	Test:       	Test_AddProviders/valid_all_supported_providers
    --- FAIL: Test_AddProviders/valid_all_supported_providers (0.00s)
```

### Desired behavior

The test should pass consistently 

### Workaround

_No response_

### rad Version

PR version or main branch version 

### Operating system

_No response_

### Additional context

_No response_

### Would you like to support us?

- [ ] Yes, I would like to support you

[AB#12415](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/12415)

### PR DESCRIPTION
**Pull request by lakshmimsft**
# Description

Fix for flaky unit test. 

## Type of change

- This pull request is a minor refactor, code cleanup, test improvement, or other maintenance task and doesn't change the functionality of Radius #7638 

Fixes: #7638

### CODE REVIEW

File: pkg/recipes/terraform/config/config_test.go [hunk 1]
```diff
@@ -647,8 +647,15 @@ func Test_AddProviders(t *testing.T) {
 			err = json.Unmarshal(expectedConfigBytes, &expectedConfig)
 			require.NoError(t, err)
 
-			// This performs a deep comparison of the two maps.
-			require.Equal(t, expectedConfig, actualConfig)
+			if tc.desc == "valid all supported providers" {
+				// The AddProviders function accepts a map of UCPConfigured providers. As maps in Go do not guarantee iteration order, the sequence of providers in the resulting configuration can vary.
+				// The mock call to BuildConfig() anticipates a specific provider configuration output in a fixed order. (ln 619)
+				// Due to potential discrepancies in order, a deep comparison of the two maps is not feasible. Instead, we compare the count of provider configurations.
+				require.Equal(t, len(expectedConfig["provider"].(map[string]any)), len(actualConfig["provider"].(map[string]any)))
```
Comment (sk593) [inline pkg/recipes/terraform/config/config_test.go:654]: Is there a way to check for "contains". So we check for the existence of AWS, SQL, etc but not an exact match

File: pkg/recipes/terraform/config/config_test.go [hunk 2]
```diff
@@ -647,8 +647,15 @@ func Test_AddProviders(t *testing.T) {
 			err = json.Unmarshal(expectedConfigBytes, &expectedConfig)
 			require.NoError(t, err)
 
-			// This performs a deep comparison of the two maps.
-			require.Equal(t, expectedConfig, actualConfig)
+			if tc.desc == "valid all supported providers" {
```
Comment (ytimocin) [inline pkg/recipes/terraform/config/config_test.go:650]: I think instead of checking for a specific test, we should check the properties one by one in the actual and expected maps. @sk593's suggestion is also a good one.

File: pkg/recipes/terraform/config/config_test.go (hunk 1 above)
Comment (lakshmimsft) [reply pkg/recipes/terraform/config/config_test.go]: updated

File: pkg/recipes/terraform/config/config_test.go (hunk 2 above)
Comment (lakshmimsft) [reply pkg/recipes/terraform/config/config_test.go:617]: We cannot match values/properties of the providers for reasons i have commented. There are other unit tests that specifically test ucpProvider BuildConfig() under radius-project/radius/pkg/recipes/terraform/config/providers/kubernetes_test.go /azure_test.go/aws_test.go.

File: pkg/recipes/terraform/config/config_test.go [hunk 3]
```diff
@@ -614,8 +616,21 @@ func Test_AddProviders(t *testing.T) {
 			err = json.Unmarshal(expectedConfigBytes, &expectedConfig)
 			require.NoError(t, err)
 
-			// This performs a deep comparison of the two maps.
-			require.Equal(t, expectedConfig, actualConfig)
+			if tc.checkProviderKeys {
+				// The AddProviders function accepts a map of UCPConfigured providers. As maps in Go do not guarantee iteration order, the sequence of providers in the resulting configuration can vary.
```
Comment (sk593) [inline pkg/recipes/terraform/config/config_test.go:620]: If we sorted the two maps by the same condition, would we be able to guarantee that the iteration order is the same? i.e. sort by the name of the provider or something? Or would this change what values we want to verify?

File: pkg/recipes/terraform/config/config_test.go [hunk 4]
```diff
@@ -614,8 +616,21 @@ func Test_AddProviders(t *testing.T) {
...
+				// The mock call to BuildConfig() anticipates a specific provider configuration output in a fixed order. (ln 619)
```
Comment (kachawla) [inline pkg/recipes/terraform/config/config_test.go:621]: What does the reference to line 619 indicate?

File: pkg/recipes/terraform/config/config_test.go [hunk 5]
```diff
@@ -614,8 +616,21 @@ func Test_AddProviders(t *testing.T) {
...
+				expectedProviderMap := expectedConfig["provider"].(map[string]any)
+				actualProviderMap := actualConfig["provider"].(map[string]any)
+
+				require.Equal(t, len(expectedProviderMap), len(actualProviderMap))
+				for k := range expectedProviderMap {
+					require.Contains(t, actualProviderMap, k)
+				}
+			} else {
+				// This performs a deep comparison of the two maps.
+				require.Equal(t, expectedConfig, actualConfig)
```
Comment (kachawla) [inline pkg/recipes/terraform/config/config_test.go:632]: Is this still needed? Would previous approach of direct json string comparison work for everything else?

File: pkg/recipes/terraform/config/config_test.go [hunk 6]
```diff
@@ -316,6 +316,7 @@ func Test_AddProviders(t *testing.T) {
 		expectedUCPConfiguredProviders []map[string]any
 		useUCPProviderConfig           bool
 		expectedConfigFile             string
+		checkProviderKeys              bool
```
Comment (kachawla) [inline pkg/recipes/terraform/config/config_test.go:319]: Can you add a comment describing what types of tests should use this field?

File: pkg/recipes/terraform/config/config_test.go (hunk 5 above)
Comment (lakshmimsft) [reply pkg/recipes/terraform/config/config_test.go:632]: yes both approaches would work. I like this approach, it is less dependent on errors due to formatting discrepancies etc. so stayed with it. Do we want to revert to previous approach?

File: pkg/recipes/terraform/config/config_test.go (hunk 4 above)
Comment (lakshmimsft) [reply pkg/recipes/terraform/config/config_test.go]: typo, updated.

File: pkg/recipes/terraform/config/config_test.go [hunk 7]
```diff
@@ -316,6 +316,7 @@ func Test_AddProviders(t *testing.T) {
 		expectedUCPConfiguredProviders []map[string]any
 		useUCPProviderConfig           bool
 		expectedConfigFile             string
+		checkProviderKeys              bool // checkProviderKeys should be set to true for tests that include multiple 'expectedUCPConfiguredProviders' and have 'useUCPProviderConfig' enabled.
```
Comment (kachawla) [inline pkg/recipes/terraform/config/config_test.go:319]: Based on the description sounds like we can use the value of the other two properties for if condition instead of introducing this new property?

File: pkg/recipes/terraform/config/config_test.go (hunk 5 above)
Comment (kachawla) [reply pkg/recipes/terraform/config/config_test.go:632]: Got it, keeping this approach sounds good

File: pkg/recipes/terraform/config/config_test.go (hunk 7 above)
Comment (lakshmimsft) [reply pkg/recipes/terraform/config/config_test.go]: haah! yes, it occurred to me a bit later. updated. thanks!

File: pkg/recipes/terraform/config/config_test.go (hunk 3 above)
Comment (lakshmimsft) [reply pkg/recipes/terraform/config/config_test.go:620]: I started writing a long explanation but easier to discuss in mtg. i had thought about this. 
short ans: sorting in the test function doesn't help and updating the target function for this did not make sense for the intended functionality.

**Review by ytimocin — APPROVED** [review]
