### PR TITLE
Fix default registry path in functional tests

### LINKED ISSUE #6556: Unable to run functional tests locally
### Steps to reproduce (required)
Run a functional test locally that uses functional.GetMagpieImage() as a parameter to the bicep.

The pod fails due to missing magpie image in GHCR. I am seeing this error:-
Message: rpc error: code = NotFound desc = failed to pull and unpack image \"ghcr.io/radius-project/dev/magpiego:latest\": failed to resolve reference \"ghcr.io/radius-project/dev/magpiego:latest\": ghcr.io/radius-project/dev/magpiego:latest: not found",

### Observed behavior (required)
In GHCR, there seems to be no image with the "latest" tag. This would not be a problem in CI/CD because there we run with the pr tag.

### Desired behavior (required)
We should be able to run the functional tests locally as is.

### Workaround (optional)
Can make a local change to pick an image that exists as a workaround

### rad Version (required)

0.26.3

### Operating system (required)

macOS

## Additional context

[AB#9898](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/9898)

### PR DESCRIPTION
**Pull request by willdavsmith**
# Description

* This fixes an issue with running the functional tests locally. The tests were looking for `ghcr.io/radius-project/dev/magpiego:latest`, where it was actually published as `ghcr.io/radius-project/magpiego:latest`.

## Type of change

- This pull request is a minor refactor, code cleanup, test improvement, or other maintenance task and doesn't change the functionality of Radius (issue link optional).

Fixes: https://github.com/radius-project/radius/issues/6556

### Summary
🚀🛠️🔄

Updated default registries for functional tests. The `test/functional/testUtil.go` file and other files that use the Docker and Bicep recipe registries now point to the production environment instead of the development or staging ones.

> _To use the production environment_
> _The registries had to be sent_
> _To the Docker and Bicep_
> _In `testUtil.go` and others they did flip_
> _This pull request shows the extent_

### Walkthrough
* Change the default Docker and Bicep recipe registries for the radius project from `ghcr.io/radius-project/dev` to `ghcr.io/radius-project` ([link](https://github.com/radius-project/radius/pull/6585/files?diff=unified&w=0#diff-d7fffa085c17b99a173ae530015cc075c39419e8ff504aea56ef80eb527b3c18L76-R76), [link](https://github.com/radius-project/radius/pull/6585/files?diff=unified&w=0#diff-d7fffa085c17b99a173ae530015cc075c39419e8ff504aea56ef80eb527b3c18L94-R94))

### CODE REVIEW

File: test/functional/testUtil.go [hunk 1]
```diff
@@ -73,7 +73,7 @@ func SetDefault() (string, string) {
 	defaultDockerReg := os.Getenv("DOCKER_REGISTRY")
 	imageTag := os.Getenv("REL_VERSION")
 	if defaultDockerReg == "" {
-		defaultDockerReg = "ghcr.io/radius-project/dev"
+		defaultDockerReg = "ghcr.io/radius-project"
```
Comment (willdavsmith) [inline test/functional/testUtil.go:76]: this should still work because we set the `DOCKER_REGISTRY` environment variable to `ghcr.io/radius-project/dev` on PR. I think the only time the default is actually being used is on local functional tests runs.

**Review by kachawla — APPROVED** [review]
