### PR TITLE
Fix rad deploy to support environment resource deployment

### LINKED ISSUE #9453: Usability: Cannot create environment using `rad deploy` because environment does not exist
### Steps to reproduce

Blank Radius installation.
```
$ rad group list             
GROUP     ID

$ rad group create dev
creating resource group "dev" in workspace ""...

resource group "dev" created

$ rad workspace list              
WORKSPACE  KIND      KUBECONTEXT  ENVIRONMENT

$ rad deploy env.bicep --group dev                         
Error: no environment name or ID provided, pass in an environment name or ID

TraceId:  92ba99eee6e45da0226c3de843b5ea4d

```
Contents of env.bicep:
```
extension radius
extension radiusResources

resource dev 'Applications.Core/environments@2023-10-01-preview' = {
  name: 'dev'
  properties: {
    compute: {
      kind: 'kubernetes'   // Required. The kind of container runtime to use
      namespace: 'dev' // Required. The Kubernetes namespace in which to render application resources
    }
  }
}
```

### Observed behavior

_No response_

### Desired behavior

Environment should be created

### Workaround
```
rad env create dummy -g dev
Creating Environment...
Successfully created environment "dummy" in resource group "dev"

$ rad deploy env.bicep --group dev -e dummy                
Building env.bicep...
WARNING: The following experimental Bicep features have been enabled: Extensibility. Experimental features should be enabled for testing purposes only, as there are no guarantees about the quality or stability of these features. Do not enable these settings for any production usage, or your production environment may be subject to breaking.
Deploying template 'env.bicep' into environment 'dummy' from workspace ''...

Deployment In Progress...

Completed            dev          Applications.Core/environments

Deployment Complete

Resources:
    dev          Applications.Core/environments
```

### rad Version

❯ rad version                             
CLI Version Information:
RELEASE   VERSION   BICEP     COMMIT
edge      75372b5   0.35.1    75372b5dc51b4b396eeda4b9d95af25d210054fa

Control Plane Information:
STATUS     VERSION
Installed  0.42.42-dev

### Operating system

_No response_

### Additional context

_No response_

### Would you like to support us?

- [ ] Yes, I would like to support you

[AB#15780](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/15780)

### PR DESCRIPTION
**Pull request by kachawla**
# Description

`rad deploy` failed when deploying Bicep templates that define environment resource type without pre-creating an environment or specifying the environment name as a cli flag. This update skips environment name validation if the deployment involves creation of an environment resource, eliminating the need for redundant step of precreating an environment.

- Moved `PrepareTemplate` from `Run()` to `Validate()` to enable early resource type detection
- Added `bicep.ContainsEnvironmentResource()` to inspect compiled ARM templates for environment resources
- Environment validation conditionally skipped when template creates the environment

## Type of change

- This pull request fixes a bug in Radius and has an approved issue (issue link required).

Fixes: https://github.com/radius-project/radius/issues/9453

## Contributor checklist
Please verify that the PR meets the following requirements, where applicable:

- An overview of proposed schema changes is included in a linked GitHub issue.
    - [ ] Yes 
    - [x] Not applicable 
- A design document PR is created in the [design-notes repository](https://github.com/radius-project/design-notes/), if new APIs are being introduced.
    - [ ] Yes 
    - [x] Not applicable 
- The design document has been reviewed and approved by Radius maintainers/approvers.
    - [ ] Yes 
    - [x] Not applicable 
- A PR for the [samples repository](https://github.com/radius-project/samples) is created, if existing samples are affected by the changes in this PR.
    - [ ] Yes 
    - [x] Not applicable 
- A PR for the [documentation repository](https://github.com/radius-project/docs) is created, if the changes in this PR affect the documentation or any user facing updates are made.
    - [ ] Yes 
    - [x] Not applicable 
- A PR for the [recipes repository](https://github.com/radius-project/recipes) is created, if existing recipes are affected by the changes in this PR.
    - [ ] Yes 
    - [x] Not applicable

### CODE REVIEW

File: pkg/cli/bicep/resources.go [hunk 1]
```diff
@@ -0,0 +1,72 @@
...
+		resourceType, ok := resource["type"].(string)
+		if !ok {
+			continue
+		}
+
+		// Resource types include API version (e.g., "Radius.Core/environments@2023-10-01-preview")
+		// Check if it starts with either resource type (case-insensitive)
+		resourceTypeLower := strings.ToLower(resourceType)
+		if strings.HasPrefix(resourceTypeLower, strings.ToLower(EnvironmentResourceType)) ||
+			strings.HasPrefix(resourceTypeLower, strings.ToLower(LegacyEnvironmentResourceType)) {
```
Comment (ytimocin) [inline pkg/cli/bicep/resources.go]: Shouldn't we check for case sensitivity?

Comment (ytimocin) [reply pkg/cli/bicep/resources.go]: What if I write Applications.core/Environments in my bicep file?

File: pkg/cli/cmd/deploy/deploy.go [hunk 2]
```diff
@@ -171,66 +172,94 @@ func (r *Runner) Validate(cmd *cobra.Command, args []string) error {
...
+	r.EnvironmentNameOrID, err = cli.RequireEnvironmentNameOrID(cmd, args, *workspace)
+	if err != nil {
+		// If no environment was provided and the template creates an environment, that's okay
+		if templateCreatesEnvironment {
+			r.EnvironmentNameOrID = ""
+		} else {
+			// Otherwise, the environment is required
+			return err
+		}
+	}
```
Comment (ytimocin) [inline pkg/cli/cmd/deploy/deploy.go]: I'd check if `cli.RequireEnvironmentNameOrID` already returns empty string for the **environmentNameOrID**. If so, I'd update the code as follows:


```suggestion
	r.EnvironmentNameOrID, err = cli.RequireEnvironmentNameOrID(cmd, args, *workspace)
	if err != nil && !templateCreatesEnvironment {
		return err
	}
```

Comment (ytimocin) [reply pkg/cli/cmd/deploy/deploy.go]: I'd also check all the possible errors `cli.RequireEnvironmentNameOrID` may return. Would there be a case where we may need to return the error w/o checking if the template creates an environment. Happy to explain further offline.

File: pkg/cli/cmd/deploy/deploy.go [hunk 3]
```diff
@@ -171,66 +172,94 @@ func (r *Runner) Validate(cmd *cobra.Command, args []string) error {
...
+			}
 
-		// If we got here, it means that the error was a 404 and the user did not specify the environment name.
-		// This is fine, because an environment is not required.
-	}
+			// If the environment doesn't exist, but the user specified its name or resource id as
+			// a command-line option, return an error
+			if cli.DidSpecifyEnvironmentName(cmd, args) {
+				return clierrors.Message("The environment %q does not exist in scope %q. Run `rad env create` first. You could also provide the environment ID if the environment exists in a different group.", r.EnvironmentNameOrID, r.Workspace.Scope)
+			}
```
Comment (ytimocin) [inline pkg/cli/cmd/deploy/deploy.go]: If `r.EnvironmentNameOrID` is not an empty string, doesn't it already mean that the user has provided environment name as a flag?

Comment (ytimocin) [reply pkg/cli/cmd/deploy/deploy.go]: I believe that this clause `if cli.DidSpecifyEnvironmentName(cmd, args)` will always be true if the code reaches here.

File: pkg/cli/cmd/deploy/deploy.go [hunk 4]
```diff
@@ -272,7 +299,10 @@ func (r *Runner) Run(ctx context.Context) error {
 
 	// Create application if specified. This supports the case where the application resource
 	// is not specified in Bicep. Creating the application automatically helps us "bootstrap" in a new environment.
-	if r.ApplicationName != "" {
+	// Note: This only applies when the environment already exists. If the template is creating the environment,
+	// r.EnvironmentNameOrID will be empty and we'll skip this step (the template deployment will create
+	// whatever resources it defines).
```
Comment (ytimocin) [inline pkg/cli/cmd/deploy/deploy.go:305]: As you said here, if the user has provided an environment **r.EnvironmentNameOrID** will never be empty.

File: pkg/cli/cmd/deploy/deploy_test.go [hunk 5]
```diff
@@ -227,12 +258,44 @@ func Test_Validate(t *testing.T) {
...
+					Return(map[string]any{}, nil).
+					Times(1)
 				mocks.ApplicationManagementClient.EXPECT().
 					GetEnvironment(gomock.Any(), gomock.Any()).
 					Return(v20231001preview.EnvironmentResource{}, radcli.Create404Error()).
 					Times(1)
 			},
 		},
+		{
+			Name:          "rad deploy - template creates environment",
```
Comment (ytimocin) [inline pkg/cli/cmd/deploy/deploy_test.go]: We should add:

1. With no environment passed in and no environment resource defined in Bicep
2. With an environment passed in and no environment resource defined in Bicep
3. With no environment passed in and environment resource defined in Bicep
4. With environment passed in and environment resource defined in Bicep

File: pkg/cli/cmd/run/run_test.go [hunk 6]
```diff
@@ -445,6 +443,7 @@ func Test_Run_NoDashboard(t *testing.T) {
 			ApplicationName:     "test-application",
 			EnvironmentNameOrID: radcli.TestEnvironmentName,
 			Parameters:          map[string]map[string]any{},
+			Template:            map[string]any{}, // Template is prepared in Validate
```
Comment (ytimocin) [inline pkg/cli/cmd/run/run_test.go:573]: We also need to add more tests here if `rad run` logic has also changed like `rad deploy`.

File: test/functional-portable/cli/noncloud/env_deploy_test.go [hunk 7]
```diff
@@ -0,0 +1,112 @@
...
+	"github.com/radius-project/radius/test/rp"
+	"github.com/radius-project/radius/test/testcontext"
+	"github.com/stretchr/testify/require"
+)
+
+// Test_DeployEnvironmentTemplate verifies that an environment can be created
+// by deploying a Bicep template that defines an environment resource, without
+// pre-creating an environment or specifying the environment name via the
+// --environment flag.
+func Test_DeployEnvironmentTemplate(t *testing.T) {
```
Comment (ytimocin) [inline test/functional-portable/cli/noncloud/env_deploy_test.go:37]: Should we also use table-driven strategy here and add more cases like I mentioned above?

File: pkg/cli/bicep/resources.go (hunk 1 above)
Comment (kachawla) [reply pkg/cli/bicep/resources.go]: It is being converted to lowercase before comparison, so this is case insensitive comparison.

File: pkg/cli/cmd/deploy/deploy.go (hunk 4 above)
Comment (kachawla) [reply pkg/cli/cmd/deploy/deploy.go:305]: Not sure if I follow you, can you elaborate? The comment says that it **will** be empty.

File: test/functional-portable/cli/noncloud/env_deploy_test.go (hunk 7 above)
Comment (kachawla) [reply test/functional-portable/cli/noncloud/env_deploy_test.go:37]: This is functional test and is expensive to run. I'd not add more tests for scenarios that are easily testable through unit tests. That would be redundant.

File: pkg/cli/cmd/deploy/deploy.go (hunk 2 above)
Comment (kachawla) [reply pkg/cli/cmd/deploy/deploy.go]: Actually revisiting this code, I don't think `RequireEnvironmentNameOrID` should even be called if the template creates an environment. Resource name defined for the environment in the template should be the source of truth. So I'm thinking of updating it to 

```
// Check if the template contains an environment resource
	templateCreatesEnvironment := bicep.ContainsEnvironmentResource(r.Template)
	if !templateCreatesEnvironment {
		// Try to get environment name/ID from flags or workspace
		r.EnvironmentNameOrID, err = cli.RequireEnvironmentNameOrID(cmd, args, *workspace)
		if err != nil {
			return err
		} 
	} else {
			r.EnvironmentNameOrID = ""
	}
```

Thoughts, @ytimocin?

File: pkg/cli/cmd/deploy/deploy.go (hunk 3 above)
Comment (kachawla) [reply pkg/cli/cmd/deploy/deploy.go]: r.EnvironmentNameOrID can be non empty because the environment was defined in the workspace. But I think we should return this error on 404 in either scenario. I'll update it to always return the error.

File: pkg/cli/cmd/deploy/deploy.go (hunk 4 above)
Comment (ytimocin) [reply pkg/cli/cmd/deploy/deploy.go:305]: Yes, sorry. I was referring to my earlier comment. You can ignore this one.

File: pkg/cli/cmd/run/run_test.go (hunk 6 above)
Comment (kachawla) [reply pkg/cli/cmd/run/run_test.go:573]: added

File: pkg/cli/cmd/deploy/deploy_test.go (hunk 5 above)
Comment (kachawla) [reply pkg/cli/cmd/deploy/deploy_test.go]: added. Thanks for the review.

File: pkg/cli/cmd/deploy/deploy.go (hunk 3 above)
Comment (kachawla) [reply pkg/cli/cmd/deploy/deploy.go]: updated

File: pkg/cli/cmd/deploy/deploy.go (hunk 2 above)
Comment (kachawla) [reply pkg/cli/cmd/deploy/deploy.go]: updated

Comment (ytimocin) [reply pkg/cli/cmd/deploy/deploy.go]: looks good!

**Review by ytimocin — APPROVED** [review]
