### PR TITLE
rad group switch output

### LINKED ISSUE #7395: `rad group switch` doesn't print success message
### Steps to reproduce

1. `rad group create test`
2. `rad group switch test`
3. See there is no message saying that the group was successfully switched

### Observed behavior

image

### Desired behavior

The CLI should tell me that the switch successfully happened.

### Workaround

_No response_

### rad Version

0.31

### Operating system

_No response_

### Additional context

_No response_

### Would you like to support us?

- [ ] Yes, I would like to support you

[AB#11631](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/11631)

### PR DESCRIPTION
**Pull request by gpltaylor**
# Description
rad cli group switch output to display success message when switching output to a group

## Type of change
- This pull request fixes a bug in Radius and has an approved issue (issue link required).

Fixes: #7395

### CODE REVIEW

**Comment by gpltaylor** [comment]
UPDATE: I will look into the test. I did some manual testing but I didn't run tests locally as the change was insignificant... We live and learn.

image

**Comment by gpltaylor** [comment]
Updated and tests running successfully locally.

image

File: pkg/cli/cmd/group/groupswitch/switch_test.go [hunk 1]
```diff
@@ -156,6 +158,7 @@ func Test_Run(t *testing.T) {
 				ConnectionFactory:    &connections.MockFactory{ApplicationsManagementClient: appManagementClient},
 				Workspace:            workspace,
 				UCPResourceGroupName: "a",
+				Output:               outputSink,
```
Comment (rynowak) [inline pkg/cli/cmd/group/groupswitch/switch_test.go:161]: Can you add an assert below about the output?

Here's an example you can borrow from: https://github.com/radius-project/radius/blob/main/pkg/cli/cmd/app/delete/delete_test.go#L280

**Review by rynowak — CHANGES_REQUESTED** [review]
Could you update the test to verify the console output? Other than that change looks great!

File: pkg/cli/cmd/group/groupswitch/switch.go [hunk 2]
```diff
@@ -128,6 +131,12 @@ func (r *Runner) Run(ctx context.Context) error {
 
 		return nil
 	})
-	return err
+
```
Comment (ytimocin) [inline pkg/cli/cmd/group/groupswitch/switch.go:134]: nit: extra line can be removed

**Review by ytimocin — DISMISSED** [review]
LGTM. Thanks for your contribution!

**Comment by ytimocin** [comment]
You also need a rebase/merge with the main branch.

**Review by rynowak — APPROVED** [review]
Awesome, thanks @gpltaylor

**Comment by gpltaylor** [comment]
@rynowak hows this looking? 
Let me know if you need anything else.

**Comment by rynowak** [comment]
Th

> @rynowak hows this looking? Let me know if you need anything else.

I'm merging this now. Thanks again.
