### PR TITLE
Do not try to load recipes for a simulated environment

### LINKED ISSUE #7156: Do not try to load recipes for simulated environments
### Steps to reproduce

1. There are no recipes in the simulated environment
2. rad app deploy <bicep file> to this env
3. Deployment fails

### Observed behavior

Currently, for a simulated env, if a recipe if not found in the env, the deployment fails.

### Desired behavior

This failure is unnecessary for simulated environments as there are no output resources rendered i.e. the result with or without loading the recipe is the same. Therefore, skip the loading of recipes in the case of simulated environments

### Workaround

_No response_

### rad Version

0.30.0

### Operating system

macOS

### Additional context

_No response_

### Would you like to support us?

- [ ] Yes, I would like to support you

[AB#11143](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/11143)

### PR DESCRIPTION
**Pull request by vinayada1**
# Description

Currently, for a simulated env, if a recipe if not found in the env, the deployment fails. This is unnecessary for simulated environments as there are no output resources rendered i.e. the result with or without loading the recipe is the same. Therefore, skip the loading of recipes in the case of simulated environments

## Type of change

- This pull request fixes a bug in Radius and has an approved issue (issue link required).

Fixes: #7156

### CODE REVIEW

File: pkg/recipes/engine/engine.go [hunk 1]
```diff
@@ -119,14 +128,18 @@ func (e *engine) Delete(ctx context.Context, opts DeleteOptions) error {
...
 // Any changes to the core logic of the Delete function should be made here.
 func (e *engine) deleteCore(ctx context.Context, recipe recipes.ResourceMetadata, outputResources []rpv1.OutputResource) (*recipes.EnvironmentDefinition, error) {
-	definition, driver, err := e.getDriver(ctx, recipe)
+	configuration, err := e.options.ConfigurationLoader.LoadConfiguration(ctx, recipe)
 	if err != nil {
 		return nil, err
 	}
 
-	configuration, err := e.options.ConfigurationLoader.LoadConfiguration(ctx, recipe)
+	if configuration.Simulated {
```
Comment (kachawla) [inline pkg/recipes/engine/engine.go:136]: A log here will be helpful as well for debugging, similar to what you have above in execute.

File: pkg/recipes/driver/bicep.go [hunk 2]
```diff
@@ -126,11 +126,6 @@ func (d *bicepDriver) Execute(ctx context.Context, opts ExecuteOptions) (*recipe
 		logger.Info("using Azure provider", "deploymentID", deploymentID, "scope", providerConfig.Az.Value.Scope)
 	}
 
-	if opts.Configuration.Simulated {
```
Comment (kachawla) [inline pkg/recipes/driver/bicep.go:129]: We should delete this unit test https://github.com/radius-project/radius/blob/27c1633311f5128e9ac44b143e63761f85f6000a/pkg/recipes/driver/bicep_test.go#L381? Doesn't look like it was doing what we expected it to, since it isn't failing now. :) Same for terraform driver.

File: pkg/recipes/engine/engine.go [hunk 3]
```diff
@@ -71,14 +72,22 @@ func (e *engine) Execute(ctx context.Context, opts ExecuteOptions) (*recipes.Rec
...
+
+	configuration, err := e.options.ConfigurationLoader.LoadConfiguration(ctx, recipe)
 	if err != nil {
-		return nil, nil, err
+		return nil, nil, recipes.NewRecipeError(recipes.RecipeConfigurationFailure, err.Error(), util.RecipeSetupError, recipes.GetErrorDetails(err))
 	}
 
-	configuration, err := e.options.ConfigurationLoader.LoadConfiguration(ctx, recipe)
+	// No need to try executing the recipe if it's a simulated environment.
+	if configuration.Simulated {
```
Comment (kachawla) [inline pkg/recipes/engine/engine.go:83]: Let's add unit test for this..

**Review by kachawla — COMMENTED** [review]
Looks great! Couple of quick comments.

Do we have any functional tests for simulated environments scenarios or plan to add any?

File: pkg/recipes/driver/bicep.go (hunk 2 above)
Comment (vinayada1) [reply pkg/recipes/driver/bicep.go:129]: These tests are actually failing which is good :) But makes sense to remove them now

**Review by kachawla — COMMENTED** [review]
Thanks for addressing the feedback.

* Is there a blocker that prevented us from adding unit tests for: https://github.com/radius-project/radius/blob/ed54654b6b46c3684b9d6264b7ebc2c4f7a2c4dd/pkg/recipes/configloader/environment.go#L114
(Not directly related to this PR, but related to simulated env test coverage and the code this PR is consuming)

* Do we have any functional tests for simulated environments scenarios or plan to add any?

**Comment by vinayada1** [comment]
> Thanks for addressing the feedback.
> 
> * Is there a blocker that prevented us from adding unit tests for: https://github.com/radius-project/radius/blob/ed54654b6b46c3684b9d6264b7ebc2c4f7a2c4dd/pkg/recipes/configloader/environment.go#L114
                   Thanks for pointing out. Added one now.
>   
>   (Not directly related to this PR, but related to simulated env test coverage and the code this PR is consuming)
> * Do we have any functional tests for simulated environments scenarios or plan to add any?
                   test/functional/datastoresrp/resources/simulated_environment_test.go has some tests. There are UTs too.

**Review by kachawla — APPROVED** [review]
