### PR TITLE
Fix flaky TF recipe tests

### LINKED ISSUE #6564: Flaky test: Test_TerraformRecipe_AzureStorage (text file busy)
## Bug information

This is from a failed scheduled functional test run.

```
=== Failed
=== FAIL: test/functional/shared/resources Test_TerraformRecipe_AzureStorage/deploy_testdata/corerp-resources-terraform-azurestorage.bicep (33.39s)
    rptest.go:272: running step 0 of 1: deploy testdata/corerp-resources-terraform-azurestorage.bicep
    deployexecutor.go:80: deploying deploy testdata/corerp-resources-terraform-azurestorage.bicep from file testdata/corerp-resources-terraform-azurestorage.bicep
    cli.go:468: [heartbeat] command rad deploy /home/runner/work/radius/radius/test/functional/shared/resources/testdata/corerp-resources-terraform-azurestorage.bicep --parameters moduleServer=http://tf-module-server.radius-test-tf-module-server.svc.cluster.local --parameters appName=corerp-resources-terraform-azstorage-app is still running after 10.000181348s
2023/10/24 08:49:30 Start streaming Kubernetes logs - Pod ctnr-live-ready-6d57b5d58c-ngxv4 is in state: Running
2023/10/24 08:49:31 Start streaming Kubernetes logs - Pod friendly-ctnr-567649468c-7r89p is in state: Running
2023/10/24 08:49:31 Streaming Kubernetes logs to /home/runner/work/radius/radius/dist/container_logs/friendly-ctnr-567649468c-7r89p.friendly-ctnr.log
2023/10/24 08:49:31 Start streaming Kubernetes logs - Pod friendly-ctnr-567649468c-7r89p is in state: Running
2023/10/24 08:49:31 Start streaming Kubernetes logs - Pod friendly-ctnr-6d9654d64c-smnvf is in state: Running
    cli.go:468: [heartbeat] command rad deploy /home/runner/work/radius/radius/test/functional/shared/resources/testdata/corerp-resources-terraform-azurestorage.bicep --parameters moduleServer=http://tf-module-server.radius-test-tf-module-server.svc.cluster.local --parameters appName=corerp-resources-terraform-azstorage-app is still running after 20.00[106](https://github.com/radius-project/radius/actions/runs/6624331998/job/17993310006#step:23:107)1603s
2023/10/24 08:49:41 Start streaming Kubernetes logs - Pod controller-95b8d7747-8hvvx is in state: Running
2023/10/24 08:49:41 Start streaming Kubernetes logs - Pod controller-95b8d7747-8hvvx is in state: Running
    cli.go:468: [heartbeat] command rad deploy /home/runner/work/radius/radius/test/functional/shared/resources/testdata/corerp-resources-terraform-azurestorage.bicep --parameters moduleServer=http://tf-module-server.radius-test-tf-module-server.svc.cluster.local/ --parameters appName=corerp-resources-terraform-azstorage-app is still running after 30.001184916s
2023/10/24 08:49:50 Saved container logs to /home/runner/work/radius/radius/dist/container_logs/friendly-ctnr-567649468c-7r89p.friendly-ctnr.log
2023/10/24 08:49:51 Start streaming Kubernetes logs - Pod friendly-ctnr-567649468c-7r89p is in state: Failed
2023/10/24 08:49:51 Start streaming Kubernetes logs - Pod friendly-ctnr-567649468c-7r89p is in state: Failed
2023/10/24 08:49:51 Start streaming Kubernetes logs - Pod friendly-ctnr-567649468c-7r89p is in state: Failed
2023/10/24 08:49:51 Start streaming Kubernetes logs - Pod friendly-ctnr-567649468c-7r89p is in state: Failed
2023/10/24 08:49:51 Start streaming Kubernetes logs - Pod friendly-rds-ctnr-58c85c867b-brkd7 is in state: Running
    cli.go:415: [rad] Building /home/runner/work/radius/radius/test/functional/shared/resources/testdata/corerp-resources-terraform-azurestorage.bicep...
    cli.go:415: [rad] Deploying template '/home/runner/work/radius/radius/test/functional/shared/resources/testdata/corerp-resources-terraform-azurestorage.bicep' into environment 'kind-radius' from workspace 'kind-radius'...
    cli.go:415: [rad] 
    cli.go:415: [rad] Deployment In Progress...
    cli.go:415: [rad] 
    cli.go:415: [rad] Error: {
    cli.go:415: [rad]   "code": "DeploymentFailed",
    cli.go:415: [rad]   "message": "At least one resource deployment operation failed. Please see the details for the specific operation that failed.",
    cli.go:415: [rad]   "target": "/planes/radius/local/resourceGroups/kind-radius/providers/Microsoft.Resources/deployments/rad-deploy-fbf2cc85-a4b9-401b-8ac6-df6ead7ae332",
    cli.go:415: [rad]   "details": [
    cli.go:415: [rad]     {
    cli.go:415: [rad]       "code": "OK",
    cli.go:415: [rad]       "message": "",
    cli.go:415: [rad]       "target": "/planes/radius/local/resourceGroups/kind-radius/providers/Applications.Core/environments/corerp-resources-terraform-azstorage-env"
    cli.go:415: [rad]     },
    cli.go:415: [rad]     {
    cli.go:415: [rad]       "code": "ResourceDeploymentFailure",
    cli.go:415: [rad]       "message": "Failed",
    cli.go:415: [rad]       "target": "/planes/radius/local/resourceGroups/kind-radius/providers/Applications.Core/extenders/corerp-resources-terraform-azstorage",
    cli.go:415: [rad]       "details": [
    cli.go:415: [rad]         {
    cli.go:415: [rad]           "code": "RecipeDeploymentFailed",
    cli.go:415: [rad]           "message": "code RecipeDownloadFailed: err failed to run terraform get to download the module from source \"http://tf-module-server.radius-test-tf-module-server.svc.cluster.local//azure-storage.zip\": fork/exec /terraform/9ffafbf8-5fa0-4286-9393-02ef37220196-18dc84ac-cd34-40e3-ab7e-53d356b60393/install/terraform: text file busy",
    cli.go:415: [rad]           "details": [
    cli.go:415: [rad]             {
    cli.go:415: [rad]               "code": "RecipeDownloadFailed",
    cli.go:415: [rad]               "message": "failed to run terraform get to download the module from source \"http://tf-module-server.radius-test-tf-module-server.svc.cluster.local//azure-storage.zip\": fork/exec /terraform/9ffafbf8-5fa0-4286-9393-02ef37220196-18dc84ac-cd34-40e3-ab7e-53d356b60393/install/terraform: text file busy"
    cli.go:415: [rad]             }
    cli.go:415: [rad]           ]
    cli.go:415: [rad]         }
    cli.go:415: [rad]       ]
    cli.go:415: [rad]     },
    cli.go:415: [rad]     {
    cli.go:415: [rad]       "code": "OK",
    cli.go:415: [rad]       "message": "",
    cli.go:415: [rad]       "target": "/planes/radius/local/resourceGroups/kind-radius/providers/Applications.Core/applications/corerp-resources-terraform-azstorage-app"
    cli.go:415: [rad]     }
    cli.go:415: [rad]   ]
    cli.go:415: [rad] }
    cli.go:415: [rad] 
    cli.go:415: [rad] TraceId:  8773b8c95cc25eaef5b0bb576315fd41
    cli.go:415: [rad] 
    cli.go:415: [rad] 
    deployexecutor.go:83: 
        	Error Trace:	/home/runner/work/radius/radius/test/step/deployexecutor.go:83
        	            				/home/runner/work/radius/radius/test/functional/shared/rptest.go:273
        	Error:      	Received unexpected error:
        	            	code DeploymentFailed: err At least one resource deployment operation failed. Please see the details for the specific operation that failed.
        	Test:       	Test_TerraformRecipe_AzureStorage/deploy_testdata/corerp-resources-terraform-azurestorage.bicep
        	Messages:   	failed to deploy deploy testdata/corerp-resources-terraform-azurestorage.bicep
    --- FAIL: Test_TerraformRecipe_AzureStorage/deploy_testdata/corerp-resources-terraform-azurestorage.bicep (33.39s)
```

[AB#9906](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/9906)

### PR DESCRIPTION
**Pull request by sk593**
# Description

This fixes flaky Terraform tests by adding retries to verify that the TF installation is compete. The problem seems to be occurring when the TF installation hasn't completed but we proceed with calling the executable anyway  

## Type of change

- This pull request fixes a bug in Radius and has an approved issue #6564 

Fixes: #6564 

### Summary
🗑️🕑🔄

This pull request improves the terraform package by using the tfexec library for installing and executing Terraform. It also adds a new metric to measure the verification time of the installation and refactors some variable names and function calls. The changes affect the files `pkg/metrics/recipeenginemetrics.go`, `pkg/recipes/terraform/execute.go`, `pkg/recipes/terraform/install.go`, and `pkg/recipes/terraform/types.go`.

> _`terraform` package_
> _refactored with tfexec_
> _cutting duplication_

### Walkthrough
*  Add and record metric for Terraform installation verification duration ([link](https://github.com/radius-project/radius/pull/6644/files?diff=unified&w=0#diff-6403665d6373b7e2a29e5a0e1d8e52b830982dfdce21983cfd83e1c434b19046R46-R48), [link](https://github.com/radius-project/radius/pull/6644/files?diff=unified&w=0#diff-6403665d6373b7e2a29e5a0e1d8e52b830982dfdce21983cfd83e1c434b19046R127-R134))
*  Return and use *tfexec.Terraform instance instead of string path from Install function ([link](https://github.com/radius-project/radius/pull/6644/files?diff=unified&w=0#diff-41ec31c0ceb8bd50c0329b55a8d27aeba69648059faef4e785302155f4e97482L73-R73), [link](https://github.com/radius-project/radius/pull/6644/files?diff=unified&w=0#diff-41ec31c0ceb8bd50c0329b55a8d27aeba69648059faef4e785302155f4e97482L85-L90), [link](https://github.com/radius-project/radius/pull/6644/files?diff=unified&w=0#diff-41ec31c0ceb8bd50c0329b55a8d27aeba69648059faef4e785302155f4e97482L122-R116), [link](https://github.com/radius-project/radius/pull/6644/files?diff=unified&w=0#diff-41ec31c0ceb8bd50c0329b55a8d27aeba69648059faef4e785302155f4e97482L134-L139), [link](https://github.com/radius-project/radius/pull/6644/files?diff=unified&w=0#diff-41ec31c0ceb8bd50c0329b55a8d27aeba69648059faef4e785302155f4e97482L182-R170), [link](https://github.com/radius-project/radius/pull/6644/files?diff=unified&w=0#diff-41ec31c0ceb8bd50c0329b55a8d27aeba69648059faef4e785302155f4e97482L194-L199), [link](https://github.com/radius-project/radius/pull/6644/files?diff=unified&w=0#diff-928c8e55e3071403aec24ba60b0f8fd85ed1f95cd4a12aed4ec6da1b3dd659c6R30), [link](https://github.com/radius-project/radius/pull/6644/files?diff=unified&w=0#diff-928c8e55e3071403aec24ba60b0f8fd85ed1f95cd4a12aed4ec6da1b3dd659c6L36-R39), [link](https://github.com/radius-project/radius/pull/6644/files?diff=unified&w=0#diff-928c8e55e3071403aec24ba60b0f8fd85ed1f95cd4a12aed4ec6da1b3dd659c6L42-R45), [link](https://github.com/radius-project/radius/pull/6644/files?diff=unified&w=0#diff-928c8e55e3071403aec24ba60b0f8fd85ed1f95cd4a12aed4ec6da1b3dd659c6L48-R51), [link](https://github.com/radius-project/radius/pull/6644/files?diff=unified&w=0#diff-928c8e55e3071403aec24ba60b0f8fd85ed1f95cd4a12aed4ec6da1b3dd659c6L69-R72), [link](https://github.com/radius-project/radius/pull/6644/files?diff=unified&w=0#diff-928c8e55e3071403aec24ba60b0f8fd85ed1f95cd4a12aed4ec6da1b3dd659c6L81-R120), [link](https://github.com/radius-project/radius/pull/6644/files?diff=unified&w=0#diff-0ad85ed086350c77c3e366408120b4c3020d1cec542671ab3586fd0c34dafe6fL77-L78))

### CODE REVIEW

File: pkg/recipes/terraform/install.go [hunk 1]
```diff
@@ -78,5 +81,40 @@ func Install(ctx context.Context, installer *install.Installer, tfDir string) (s
...
 
-	return execPath, nil
+	// Create a new instance of tfexec.Terraform with current Terraform installation path
+	tf, err := NewTerraform(ctx, tfDir, execPath)
+	if err != nil {
+		return nil, err
+	}
+
+	// Verify Terraform installation is complete before proceeding
+	for attempt := 0; attempt <= installRetryCount; attempt++ {
```
Comment (sk593) [inline pkg/recipes/terraform/install.go:91]: It seems like the issue is that the Terraform installation doesn't complete fully before we try to use the executable. The idea is to wrap checking the TF version with retries so we only continue when we know for sure that calling the executable won't cause issues

File: pkg/recipes/terraform/install.go [hunk 2]
```diff
@@ -78,5 +81,40 @@ func Install(ctx context.Context, installer *install.Installer, tfDir string) (s
...
+		_, _, err = tf.Version(ctx, false)
+		if err != nil {
+			if attempt < installRetryCount {
+				logger.Info(fmt.Sprintf("Failed to verify Terraform installation: %s. Retrying after %d seconds", err.Error(), retryDelaySecs))
+				metrics.DefaultRecipeEngineMetrics.RecordTerraformInstallVerificationDuration(ctx, installStartTime,
```
Comment (sk593) [inline pkg/recipes/terraform/install.go:96]: Adding metrics so we can track how long installation/verification takes in these edge cases. We can adjust the retry count and duration if needed

File: pkg/metrics/recipeenginemetrics.go [hunk 3]
```diff
@@ -43,6 +43,9 @@ const (
 	// terraformInitializationDuration is the metric name for the Terraform initialization duration.
 	terraformInitializationDuration = "recipe.tf.init.duration"
 
+	// terraformVerficiationDuration is the metric name for the Terraform installation verification duration.
```
Comment (ytimocin) [inline pkg/metrics/recipeenginemetrics.go:46]: names do not match

File: pkg/recipes/terraform/install.go (hunk 1 above)
Comment (ytimocin) [reply pkg/recipes/terraform/install.go:91]: If `installRetryCount` is 5 then this will run 6 times. Why not make it just less than so that we can also get rid of the `if case` in the loop?

File: pkg/recipes/terraform/install.go [hunk 4]
```diff
@@ -78,5 +81,40 @@ func Install(ctx context.Context, installer *install.Installer, tfDir string) (s
...
+	tf, err := NewTerraform(ctx, tfDir, execPath)
+	if err != nil {
+		return nil, err
+	}
+
+	// Verify Terraform installation is complete before proceeding
+	for attempt := 0; attempt <= installRetryCount; attempt++ {
+		_, _, err = tf.Version(ctx, false)
+		if err != nil {
+			if attempt < installRetryCount {
```
Comment (ytimocin) [inline pkg/recipes/terraform/install.go:94]: Why do we need to do it this way?

File: pkg/recipes/terraform/install.go (hunk 2 above)
Comment (ytimocin) [reply pkg/recipes/terraform/install.go:96]: This may create a few metrics for just one installation. Is that the goal?

File: pkg/recipes/terraform/install.go [hunk 5]
```diff
@@ -78,5 +81,40 @@ func Install(ctx context.Context, installer *install.Installer, tfDir string) (s
...
+
+	metrics.DefaultRecipeEngineMetrics.RecordTerraformInstallVerificationDuration(ctx, installStartTime,
+		[]attribute.KeyValue{
+			metrics.TerraformVersionAttrKey.String("latest"),
+			metrics.OperationStateAttrKey.String(metrics.SuccessfulOperationState),
+		},
+	)
+
+	// Configure Terraform logs once Terraform installation is complete
+	configureTerraformLogs(ctx, tf)
```
Comment (ytimocin) [inline pkg/recipes/terraform/install.go:117]: Why was this moved here?

File: pkg/recipes/terraform/install.go [hunk 6]
```diff
@@ -78,5 +81,40 @@ func Install(ctx context.Context, installer *install.Installer, tfDir string) (s
 
 	logger.Info(fmt.Sprintf("Terraform latest version installed to: %q", execPath))
 
-	return execPath, nil
+	// Create a new instance of tfexec.Terraform with current Terraform installation path
+	tf, err := NewTerraform(ctx, tfDir, execPath)
```
Comment (ytimocin) [inline pkg/recipes/terraform/install.go:85]: Why don't we do the retry in this function?

File: pkg/recipes/terraform/install.go [hunk 7]
```diff
@@ -78,5 +81,40 @@ func Install(ctx context.Context, installer *install.Installer, tfDir string) (s
...
+					[]attribute.KeyValue{
+						metrics.TerraformVersionAttrKey.String("latest"),
+						metrics.OperationStateAttrKey.String(metrics.FailedOperationState),
+					},
+				)
+				time.Sleep(time.Duration(retryDelaySecs) * time.Second)
+				continue
+			}
+			return nil, err
+		}
```
Comment (vishwahiremat) [inline pkg/recipes/terraform/install.go:106]: can we add a `break` statement here if err is nil?

File: pkg/recipes/terraform/install.go (hunk 6 above)
Comment (sk593) [reply pkg/recipes/terraform/install.go:85]: The problem happens when we try to use the terraform executable (i.e. `tf`). So we don't want to retry the creation of it, just when it's first used

File: pkg/recipes/terraform/install.go (hunk 4 above)
Comment (sk593) [reply pkg/recipes/terraform/install.go:94]: We want to return an error if we've hit the max retries. The if statement is there to check if we've the max retires and we still have an error. I can't respond to the last comment directly for some reason but we need the `if case` for this reason

File: pkg/recipes/terraform/install.go (hunk 5 above)
Comment (sk593) [reply pkg/recipes/terraform/install.go:117]: This is where the original error was being thrown because in `configureTerraformLogs` we were using the TF executable to set logs. This is being separated out so we can first verify the TF installation completes and then continue on with configuring logs, downloading modules, etc

File: pkg/recipes/terraform/install.go (hunk 7 above)
Comment (sk593) [reply pkg/recipes/terraform/install.go:109]: Added this

File: pkg/metrics/recipeenginemetrics.go (hunk 3 above)
Comment (sk593) [reply pkg/metrics/recipeenginemetrics.go]: Fixed

File: pkg/recipes/terraform/install.go (hunk 2 above)
Comment (sk593) [reply pkg/recipes/terraform/install.go:99]: I think it'd be good to track how many times we end up needing to retry and what was the duration. Since this is a flaky test we can't really repro to get the right number of retries and duration between each so this will help us get a gauge. Do you think there's a better place to put the metrics to track that info?

File: pkg/recipes/terraform/install.go (hunk 1 above)
Comment (sk593) [reply pkg/recipes/terraform/install.go:91]: Don't think we can completely get rid of the if case since that's how we decide whether to retry or not. The retry count is 5, not necessarily the number of times it runs so after the 5th retry, we'd return the error if it's still happening. We can change this number though, 5 just seemed like a logical starting point. Thoughts on the right value for that? @kachawla

File: pkg/recipes/terraform/install.go [hunk 8]
```diff
@@ -78,5 +81,43 @@ func Install(ctx context.Context, installer *install.Installer, tfDir string) (s
...
+	}
+
+	metrics.DefaultRecipeEngineMetrics.RecordTerraformInstallVerificationDuration(ctx, installStartTime,
```
Comment (kachawla) [inline pkg/recipes/terraform/install.go:112]: Should this be moved after this check `if err == nil {` at L93?

File: pkg/recipes/terraform/install.go (hunk 1 above)
Comment (kachawla) [reply pkg/recipes/terraform/install.go:91]: Yeah we don't really have a good way to decide on the right retry count until we have some metrics on how long it takes for installation to complete.

@sk593, I think @ytimocin wasn't asking the reasoning for retry count value, but instead that this loop will be executed retryCount+1 times since it starts at 0 `for attempt := 0; attempt <= installRetryCount; attempt++ {`

File: pkg/metrics/recipeenginemetrics.go [hunk 9]
```diff
@@ -43,6 +43,9 @@ const (
 	// terraformInitializationDuration is the metric name for the Terraform initialization duration.
 	terraformInitializationDuration = "recipe.tf.init.duration"
 
+	// terraformInstallVerficiationDuration is the metric name for the Terraform installation verification duration.
+	terraformInstallVerficiationDuration = "recipe.tf.install.verification.duration"
```
Comment (kachawla) [inline pkg/metrics/recipeenginemetrics.go:47]:
```suggestion
	terraformInstallVerificiationDuration = "recipe.tf.install.verification.duration"
```

[the remark this answers is not in the document]
Comment (sk593) [reply pkg/metrics/recipeenginemetrics.go:47]: Yes, this tracks how long the installation takes to be fully complete (i.e. we can use the executable with no problems) from the time we start installation

File: pkg/recipes/terraform/install.go (hunk 8 above)
Comment (sk593) [reply pkg/recipes/terraform/install.go:112]: I'm not sure that it'd make much a difference time wise since this line will be hit right after the break, but moved it up just in case

File: pkg/metrics/recipeenginemetrics.go (hunk 9 above)
Comment (sk593) [reply pkg/metrics/recipeenginemetrics.go]: Fixed

File: pkg/recipes/terraform/install.go [hunk 10]
```diff
@@ -78,5 +81,43 @@ func Install(ctx context.Context, installer *install.Installer, tfDir string) (s
...
+				metrics.DefaultRecipeEngineMetrics.RecordTerraformInstallVerificationDuration(ctx, installStartTime,
+					[]attribute.KeyValue{
+						metrics.TerraformVersionAttrKey.String("latest"),
+						metrics.OperationStateAttrKey.String(metrics.FailedOperationState),
+					},
+				)
+				time.Sleep(time.Duration(retryDelaySecs) * time.Second)
+				continue
+			}
+			return nil, err
```
[the remark this answers is not in the document]
Comment (sk593) [reply pkg/recipes/terraform/install.go]: Updated

File: pkg/recipes/terraform/install.go [hunk 11]
```diff
@@ -78,5 +81,42 @@ func Install(ctx context.Context, installer *install.Installer, tfDir string) (s
...
+		if err == nil {
+			metrics.DefaultRecipeEngineMetrics.RecordTerraformInstallVerificationDuration(ctx, installStartTime,
+				[]attribute.KeyValue{
+					metrics.TerraformVersionAttrKey.String("latest"),
+					metrics.OperationStateAttrKey.String(metrics.SuccessfulOperationState),
+				},
+			)
+			break
+		}
+		if err != nil {
```
Comment (ytimocin) [inline pkg/recipes/terraform/install.go:102]: We don't need this. If `tf.Version` is successful, then it is going to go into the `if err == nil`, and then the break will exit the for loop. Each time `tf.Version` returns an error, it will go to the second if. So, we don't need the second if I think.

tf.Version
=> Success => Exit for loop
=> Failure => Sleep and retry

**Review by ytimocin — COMMENTED** [review]
Were we able to test and approve this solution?

File: pkg/recipes/terraform/install.go (hunk 11 above)
Comment (sk593) [reply pkg/recipes/terraform/install.go:102]: Good catch, this originally was only checking `err != nil` but I missed removing that check once `err == nil` was added

**Comment by sk593** [comment]
> Were we able to test and approve this solution?

Functional tests are passing with this update. There's not really a good way to manually reproduce the error found in the logs. We just know that the executable text file is busy when we try to use it, so we'd have to find some way to time using the executable when we know that it's not fully installed yet for a repro. The idea is that we verify everything is installed correctly first (and track that with metrics), and then proceed with any other TF deployment steps to mitigate this issue

File: pkg/recipes/terraform/install.go (hunk 1 above)
Comment (sk593) [reply pkg/recipes/terraform/install.go]: My bad, I misunderstood the question. I updated the attempts to start at 1 so we get the proper count

**Review by kachawla — DISMISSED** [review]

File: pkg/recipes/terraform/install.go (hunk 1 above)
Comment (ytimocin) [reply pkg/recipes/terraform/install.go]: Yes, @kachawla thanks for the clarification! We can also start from 0 and go to `upperLimit - 1` @sk593.

File: pkg/recipes/terraform/install.go [hunk 12]
```diff
@@ -78,5 +81,40 @@ func Install(ctx context.Context, installer *install.Installer, tfDir string) (s
...
+				[]attribute.KeyValue{
+					metrics.TerraformVersionAttrKey.String("latest"),
+					metrics.OperationStateAttrKey.String(metrics.SuccessfulOperationState),
+				},
+			)
+			break
+		}
+		if attempt < installVerificationRetryCount {
+			logger.Info(fmt.Sprintf("Failed to verify Terraform installation completion: %s. Retrying after %d seconds", err.Error(), installVerificationRetryDelaySecs))
+			metrics.DefaultRecipeEngineMetrics.RecordTerraformInstallVerificationDuration(ctx, installStartTime,
```
Comment (ytimocin) [inline pkg/recipes/terraform/install.go:104]: The last try will not be logged in this case.

Comment (ytimocin) [reply pkg/recipes/terraform/install.go:104]: Case: Let's imagine that the **attempt** starts from 1 and the **installVerificationRetryCount** is 5. The fifth run will not go into this `if case` and therefore not be logged.

**Review by ytimocin — DISMISSED** [review]

File: pkg/recipes/terraform/install.go (hunk 12 above)
Comment (sk593) [reply pkg/recipes/terraform/install.go:104]: Going to do it from 0 to retry-1 as suggested so there's `installVerificationRetryCount` logs

File: pkg/recipes/terraform/install.go (hunk 1 above)
Comment (sk593) [reply pkg/recipes/terraform/install.go]: Going to use the suggested so we get the proper number of logs

File: pkg/recipes/terraform/install.go (hunk 12 above)
Comment (sk593) [reply pkg/recipes/terraform/install.go:104]: Actually, there needs to be an attempt 5 for the if case to trigger in the case of an error. So I think the best way to do it is to stick to the original 0 to `installVerificationRetryCount`

**Review by ytimocin — APPROVED** [review]

**Review by kachawla — APPROVED** [review]
