### PR TITLE
Fixes #7391 - fixing error in rad group show for no args

### LINKED ISSUE #7391: `rad group show` doesn't show the current group
### Steps to reproduce

Not sure if this is expected but unlike `rad workspace show` or `rad env show`, `rad group show` doesn't show the current/active group.

### Observed behavior

image

### Desired behavior

`rad group show` should show the current/active group.

### Workaround

_No response_

### rad Version

RELEASE   VERSION   BICEP     COMMIT
0.31.0    v0.31.0   0.31.0    3fa840730295681733357e7c94e6813d04cfae6d

### Operating system

macOS, Apple M1 Pro, Sonoma 14.4

### Additional context

_No response_

### Would you like to support us?

- [ ] Yes, I would like to support you

[AB#11624](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/11624)

### PR DESCRIPTION
**Pull request by superbeeny**
# Description

Fixes #7391 - fixes issue with error incorrectly returned for `rad group show` with no group name argument.

## Type of change
- This pull request fixes a bug in Radius and has an approved issue (issue link required).

Fixes: #7391

### CODE REVIEW

**Comment by rynowak** [comment]
Functional test failure is unrelated, and seems to be impacting all of our runs. We're investigating offline.

File: pkg/cli/cmd/group/show/show.go [hunk 1]
```diff
@@ -99,9 +101,18 @@ func (r *Runner) Validate(cmd *cobra.Command, args []string) error {
 	if format == "" {
 		format = "table"
 	}
-	resourcegroup, err := cli.RequireUCPResourceGroup(cmd, args)
-	if err != nil {
-		return err
+	var resourcegroup string
```
Comment (nithyatsu) [inline pkg/cli/cmd/group/show/show.go:104]: we use camelCase for variable names. Therefore, this would be resourceGroup

File: pkg/cli/cmd/group/show/show.go [hunk 2]
```diff
@@ -99,9 +101,18 @@ func (r *Runner) Validate(cmd *cobra.Command, args []string) error {
...
+	if len(args) == 1 {
+		resourcegroup, err = cli.RequireUCPResourceGroup(cmd, args)
+		if err != nil {
+			return err
+		}
+	} else {
+		id, err := resources.ParseScope(workspace.Scope)
+		if err != nil {
+			return err
+		}
```
Comment (nithyatsu) [inline pkg/cli/cmd/group/show/show.go:114]: I think, it would be a good idea to add a function that checks for whether an UCP resource group is provided as an argument or if a default environment is set in the workspace in /radius/pkg/cli/clivalidation.go and use it here. We have similar functionality for environments here https://github.com/radius-project/radius/blob/5d82f27c694f972e310fc82d553c7bc2716f95c7/pkg/cli/clivalidation.go#L50
This way the logic would be reusable elsewhere too.

**Comment by nithyatsu** [comment]
Thank you so much for contributing to Radius, Nick! I left a couple of comments.

File: pkg/cli/cmd/group/show/show.go (hunk 2 above)
Comment (superbeeny) [reply pkg/cli/cmd/group/show/show.go:114]: Makes sense to me

**Review by rynowak — APPROVED** [review]

**Review by ytimocin — APPROVED** [review]

**Review by nithyatsu — APPROVED** [review]
