### PR TITLE
Fix nil pointer dereference in deployment reconciler

### LINKED ISSUE #6841: `Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference` error in the controller pod
## Bug information
I have observed this error message in the functional test runs of some PRs in the controller pod.

`
{"severity":"info","timestamp":"2023-11-22T16:40:35.409Z","name":"controller.controller","caller":"controller/controller.go:114","message":"Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference","serviceName":"controller","version":"edge","hostName":"controller-84f587c5d6-kqhcf","controller":"deployment","controllerGroup":"apps","controllerKind":"Deployment","Deployment":{"name":"dapr-sts-manual-redis","namespace":"default-daprrp-rs-statestore-manual"},"namespace":"default-daprrp-rs-statestore-manual","name":"dapr-sts-manual-redis","reconcileID":"276efd5d-463d-41b1-8b3c-30c5312ed1fd"}
`

panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x17b5417]

goroutine 133 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:115 +0x1e5
panic({0x1974860?, 0x2cda2d0?})
	/opt/hostedtoolcache/go/1.21.4/x64/src/runtime/panic.go:914 +0x21f
github.com/radius-project/radius/pkg/controller/reconciler.(*DeploymentReconciler).Reconcile(0xc0000cb100, {0x1ed8998, 0xc000908660}, {{{0xc00095dcb0?, 0x0?}, {0xc000691068?, 0x410745?}}})
	/home/runner/work/radius/radius/pkg/controller/reconciler/deployment_reconciler.go:110 +0x3b7
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x1ed8998?, {0x1ed8998?, 0xc000908660?}, {{{0xc00095dcb0?, 0x18a9e60?}, {0xc000691068?, 0x1ec7010?}}})
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:118 +0xb7
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0001ad040, {0x1ed89d0, 0xc0006ec870}, {0x1a1fb00?, 0xc0005b78c0?})
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:314 +0x365
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0001ad040, {0x1ed89d0, 0xc0006ec870})
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:265 +0x1c9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:226 +0x79
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2 in goroutine 101
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:222 +0x565

### Steps to reproduce (required)
1. Create a PR or run functional tests locally (the latter needs confirmation)
2. Check controller pod logs
3. See the panic

### Observed behavior (required)
Error in the controller pod.

### Desired behavior (required)
No panic

### rad Version (required)
PR

### Operating system (required)
PR

## Additional context
[msgrp_container_logs.zip](https://github.com/radius-project/radius/files/13443632/msgrp_container_logs.zip)
[daprrp_container_logs.zip](https://github.com/radius-project/radius/files/13443633/daprrp_container_logs.zip)

[AB#10470](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/10470)

### PR DESCRIPTION
**Pull request by ytimocin**
# Description
Fix nil pointer dereference in deployment reconciler.

## Type of change
- This pull request fixes a bug in Radius and has an approved issue (issue link required).
Fixes: #6841 

### Summary
🐛🚑💅

Fix nil pointer bug and improve formatting in `reconciler` package. The pull request updates the `deployment_reconciler` logic to avoid a potential crash and applies consistent code style to the `reconciler` files.

> _`deployment_reconciler`_
> _Fixes a nil pointer bug_
> _Code is more tidy_

### Walkthrough
*  Prevent nil pointer dereference when accessing status annotation ([link](https://github.com/radius-project/radius/pull/6853/files?diff=unified&w=0#diff-87a7dfa06c174a6b41b671b2cfffb84c81e481881baec866a026e7dd00db8195L110-R110))
*  Remove unnecessary blank line from `reconciler` package ([link](https://github.com/radius-project/radius/pull/6853/files?diff=unified&w=0#diff-87a7dfa06c174a6b41b671b2cfffb84c81e481881baec866a026e7dd00db8195L184))

### CODE REVIEW

File: pkg/controller/reconciler/deployment_reconciler.go [hunk 1]
```diff
@@ -126,6 +126,7 @@ func (r *DeploymentReconciler) Reconcile(ctx context.Context, req ctrl.Request)
 
 	// If the Deployment is being deleted **or** if Radius is no longer enabled, then we should
 	// clean up any Radius state.
+	// FIXME: If the DeletionTimestamp is not nil, does it mean that Configuration and/or Status will also not be nil?
```
Comment (rynowak) [inline pkg/controller/reconciler/deployment_reconciler.go:129]: This is possible in the following case:

- Deletion of the `Deployment` is in progress (`DeletionTimestamp != nil`)
- The `Deployment` is not using Radius `Configuration == nil`
- The `Deployment` was not previously using Radius `Status == nil`

File: pkg/controller/reconciler/deployment_reconciler.go [hunk 2]
```diff
@@ -250,12 +250,14 @@ func (r *DeploymentReconciler) reconcileUpdate(ctx context.Context, deployment *
 	}
 
 	environmentName := "default"
-	if annotations.Configuration.Environment != "" {
+	// What if Configuration is nil?
```
Comment (rynowak) [inline pkg/controller/reconciler/deployment_reconciler.go:253]: I don't mind the extra check, but this method will not be called when the configuration is nil.

File: pkg/controller/reconciler/deployment_reconciler.go [hunk 3]
```diff
@@ -465,7 +477,9 @@ func (r *DeploymentReconciler) startPutOrDeleteOperationIfNeeded(ctx context.Con
 
 func (r *DeploymentReconciler) startDeleteOperationIfNeeded(ctx context.Context, deployment *appsv1.Deployment, annotations *deploymentAnnotations) (Poller[v20231001preview.ContainersClientDeleteResponse], error) {
 	logger := ucplog.FromContextOrDiscard(ctx)
-	if annotations.Status.Container == "" {
+
+	// What if Status is nil?
+	if annotations.Status == nil || (annotations.Status != nil && annotations.Status.Container == "") {
```
Comment (rynowak) [inline pkg/controller/reconciler/deployment_reconciler.go:482]: This will never be called when `Status` is nil.

File: pkg/controller/reconciler/annotations.go [hunk 4]
```diff
@@ -84,7 +84,7 @@ type deploymentStatus struct {
 // This includes the configuration specified by the user, the hash of the configuration, and the status.
 func readAnnotations(deployment *appsv1.Deployment) (*deploymentAnnotations, error) {
 	if deployment.Annotations == nil {
-		return nil, nil
+		return &deploymentAnnotations{}, nil
```
Comment (rynowak) [inline pkg/controller/reconciler/annotations.go:87]: Before we start changing things, do we have a repro for this? Is it possible to add or tweak a test that will reproduce the failure.

Comment (rynowak) [reply pkg/controller/reconciler/annotations.go:87]: Asking because I'm not sure I understand the cause yet. Crashes like this are useful because they probably indicate a logic error.

**Review by rynowak — APPROVED** [review]
