### PR TITLE
Remove bicep download authentication credentials

### LINKED ISSUE #6597: Failed to install rad-bicep Failed to install Radius CLI (Error code 403)
### Steps to reproduce (required)
Run install script for MacOS (Silicon) `curl -fsSL "https://raw.githubusercontent.com/radius-project/radius/main/deploy/install.sh" | /bin/bash`. This curl is taken from [here](https://docs.radapp.io/getting-started/#2-install-radius-cli).

### Observed behavior (required)
```
> curl -fsSL "https://raw.githubusercontent.com/radius-project/radius/main/deploy/install.sh" | /bin/bash
Getting the latest Radius CLI...
Your system is darwin_arm64
Installing Radius CLI...

Installing v0.26.8 Radius CLI...
Downloading https://github.com/radius-project/radius/releases/download/v0.26.8/rad_darwin_arm64...
Password:
rad installed into /usr/local/bin successfully
Installing rad-bicep ("rad bicep download")...
Downloading Bicep for channel 0.26...
Attempt 1 failed to download bicep: failed to resolve 0.26: GET "https://ghcr.io/v2/radius-project/radius/bicep/rad-bicep/macos-arm64/manifests/0.26": GET "https://ghcr.io/token?scope=repository%3Aradius-project%2Fradius%2Fbicep%2Frad-bicep%2Fmacos-arm64%3Apull&service=ghcr.io": response status code 403: denied: denied
Retrying...Attempt 2 failed to download bicep: failed to resolve 0.26: GET "https://ghcr.io/v2/radius-project/radius/bicep/rad-bicep/macos-arm64/manifests/0.26": GET "https://ghcr.io/token?scope=repository%3Aradius-project%2Fradius%2Fbicep%2Frad-bicep%2Fmacos-arm64%3Apull&service=ghcr.io": response status code 403: denied: denied
Retrying...Attempt 3 failed to download bicep: failed to resolve 0.26: GET "https://ghcr.io/v2/radius-project/radius/bicep/rad-bicep/macos-arm64/manifests/0.26": GET "https://ghcr.io/token?scope=repository%3Aradius-project%2Fradius%2Fbicep%2Frad-bicep%2Fmacos-arm64%3Apull&service=ghcr.io": response status code 403: denied: denied
Retrying...Attempt 4 failed to download bicep: failed to resolve 0.26: GET "https://ghcr.io/v2/radius-project/radius/bicep/rad-bicep/macos-arm64/manifests/0.26": GET "https://ghcr.io/token?scope=repository%3Aradius-project%2Fradius%2Fbicep%2Frad-bicep%2Fmacos-arm64%3Apull&service=ghcr.io": response status code 403: denied: denied
Retrying...Attempt 5 failed to download bicep: failed to resolve 0.26: GET "https://ghcr.io/v2/radius-project/radius/bicep/rad-bicep/macos-arm64/manifests/0.26": GET "https://ghcr.io/token?scope=repository%3Aradius-project%2Fradius%2Fbicep%2Frad-bicep%2Fmacos-arm64%3Apull&service=ghcr.io": response status code 403: denied: denied
Retrying...Attempt 6 failed to download bicep: failed to resolve 0.26: GET "https://ghcr.io/v2/radius-project/radius/bicep/rad-bicep/macos-arm64/manifests/0.26": GET "https://ghcr.io/token?scope=repository%3Aradius-project%2Fradius%2Fbicep%2Frad-bicep%2Fmacos-arm64%3Apull&service=ghcr.io": response status code 403: denied: denied
Retrying...Attempt 7 failed to download bicep: failed to resolve 0.26: GET "https://ghcr.io/v2/radius-project/radius/bicep/rad-bicep/macos-arm64/manifests/0.26": GET "https://ghcr.io/token?scope=repository%3Aradius-project%2Fradius%2Fbicep%2Frad-bicep%2Fmacos-arm64%3Apull&service=ghcr.io": response status code 403: denied: denied
Retrying...Attempt 8 failed to download bicep: failed to resolve 0.26: GET "https://ghcr.io/v2/radius-project/radius/bicep/rad-bicep/macos-arm64/manifests/0.26": GET "https://ghcr.io/token?scope=repository%3Aradius-project%2Fradius%2Fbicep%2Frad-bicep%2Fmacos-arm64%3Apull&service=ghcr.io": response status code 403: denied: denied
Retrying...Attempt 9 failed to download bicep: failed to resolve 0.26: GET "https://ghcr.io/v2/radius-project/radius/bicep/rad-bicep/macos-arm64/manifests/0.26": GET "https://ghcr.io/token?scope=repository%3Aradius-project%2Fradius%2Fbicep%2Frad-bicep%2Fmacos-arm64%3Apull&service=ghcr.io": response status code 403: denied: denied
Retrying...Error: failed to download bicep: failed to resolve 0.26: GET "https://ghcr.io/v2/radius-project/radius/bicep/rad-bicep/macos-arm64/manifests/0.26": GET "https://ghcr.io/token?scope=repository%3Aradius-project%2Fradius%2Fbicep%2Frad-bicep%2Fmacos-arm64%3Apull&service=ghcr.io": response status code 403: denied: denied

TraceId:  5dd55f8debd087179dbf8da34ab3ea85

Failed to install rad-bicep
Failed to install Radius CLI
For support, go to https://github.com/radius-project/radius
```

### Desired behavior (required)
Install rad

### rad Version (required)
NA

### Operating system (required)
MacOS Ventura 13.6 (M2)

## Additional context
It is strange to get a 403.

[AB#9965](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/9965)

### PR DESCRIPTION
**Pull request by sk593**
# Description

This removes authentication to GHCR since anonymous pulls are enabled. 

## Type of change

- This pull request fixes a bug in Radius and has an approved issue #6597 

Partially addresses: #6597 

### Summary
🗑️🔐📥

Refactored and enhanced binary download functionality in `pkg/cli/tools/binary_tools.go`. Removed unused code and streamlined authentication.

> _`DownloadToFolder`_
> _Cleans imports, auth, and code_
> _A fresh spring refactor_

### Walkthrough
* Remove unnecessary imports of `oras-credentials-go` and `auth` packages ([link](https://github.com/radius-project/radius/pull/6615/files?diff=unified&w=0#diff-0bb0df6a87062e6fad23c5f50750cb65e5e6e03112e526341f38a0e42ee06d6bL26-R29)) to simplify dependencies and reduce code complexity

### CODE REVIEW

File: pkg/cli/tools/binary_tools.go [hunk 1]
```diff
@@ -154,20 +151,6 @@ func DownloadToFolder(filepath string) error {
...
 
-	// Create credentials to authenticate to repository
-	ds, err := credentials.NewStoreFromDocker(credentials.StoreOptions{
-		AllowPlaintextPut: true,
-	})
-	if err != nil {
-		return err
-	}
-
-	repo.Client = &auth.Client{
```
Comment (sk593) [inline pkg/cli/tools/binary_tools.go:165]: If a client isn't specified, the oras client uses the default auth client (which uses the same default client/cache with an EmptyCredential instead of a set value) https://github.com/oras-project/oras-go/blob/062ed0e058f87a9661dfb5db41e8e72f74dfffe2/registry/remote/auth/client.go#L35

**Review by nithyatsu — APPROVED** [review]

**Review by rynowak — APPROVED** [review]

**Review by kachawla — APPROVED** [review]

**Comment by AaronCrawfis** [comment]
Confirmed working for me: 
image

**Review by AaronCrawfis — APPROVED** [review]
