### PR TITLE
Waiting for the cache to sync in flux test

### LINKED ISSUE #9235: Flaky test: `Test_FluxController_Basic`: the cache is not started, can not read objects
### Steps to reproduce

Sometimes in the functional-test-noncloud, we see this issue.

### Observed behavior

_No response_

### Desired behavior

Test should pass

### Workaround

re-run test

### rad Version

CI

### Operating system

_No response_

### Additional context

_No response_

### Would you like to support us?

- [ ] Yes, I would like to support you

### PR DESCRIPTION
**Pull request by ytimocin**
# Description

Fixes a race condition in **flux_controller_test.go** where tests could attempt to use the Kubernetes client before the controller manager's cache was fully synchronized. The fix ensures synchronization by waiting for the manager's election signal before proceeding to wait for the cache sync.

## Type of change
- This pull request fixes a bug in Radius and has an approved issue (issue link required).

Fixes: #9235 

## Contributor checklist
Please verify that the PR meets the following requirements, where applicable:

- An overview of proposed schema changes is included in a linked GitHub issue.
    - [ ] Yes
    - [x] Not applicable
- A design document PR is created in the [design-notes repository](https://github.com/radius-project/design-notes/), if new APIs are being introduced.
    - [ ] Yes
    - [x] Not applicable
- The design document has been reviewed and approved by Radius maintainers/approvers.
    - [ ] Yes
    - [x] Not applicable
- A PR for the [samples repository](https://github.com/radius-project/samples) is created, if existing samples are affected by the changes in this PR.
    - [ ] Yes
    - [x] Not applicable
- A PR for the [documentation repository](https://github.com/radius-project/docs) is created, if the changes in this PR affect the documentation or any user facing updates are made.
    - [ ] Yes
    - [x] Not applicable
- A PR for the [recipes repository](https://github.com/radius-project/recipes) is created, if existing recipes are affected by the changes in this PR.
    - [ ] Yes
    - [x] Not applicable

### CODE REVIEW

File: pkg/controller/reconciler/flux_controller_test.go [hunk 1]
```diff
@@ -149,6 +149,7 @@ func setupFluxControllerTest(t *testing.T, opts setupFluxControllerTestOptions,
 		Metrics: server.Options{
 			BindAddress: "0",
 		},
+		LeaderElection: false,
```
Comment (willdavsmith) [inline pkg/controller/reconciler/flux_controller_test.go:152]: Is this only supposed to be one line? I saw before that there were a few changes

**Review by willdavsmith — APPROVED** [review]
Let's run a few times to make sure it's not flaky. Thanks for the change!

File: pkg/controller/reconciler/flux_controller_test.go (hunk 1 above)
Comment (ytimocin) [reply pkg/controller/reconciler/flux_controller_test.go:152]: I ran into some other issues with the leader election and cache sync wait logic. I checked the other test that creates a manager and saw that the difference was this line. Let's test it this way and see if we will run into issues.
