### PR TITLE
Changes for creating env namspace on the server side and functional test for validating existing keyword with portable resources.

### LINKED ISSUE #8464: Kubernetes namespace for the environment is not being created during deployment
### Steps to reproduce

1. Create a fresh Kubernetes cluster
2. Install Radius using `rad install kubernetes`
3. Try to create an environment using the following Bicep file:

```
extension radius

@description('Specifies the location for resources.')
param location string = 'global'

resource env 'Applications.Core/environments@2023-10-01-preview' = {
  name: 'radius-test-env'
  location: location
  properties: {
    compute: {
      kind: 'kubernetes'
      resourceId: 'self'
      namespace: 'radius-test-env-ns-1'
    }
  }
}
```

### Observed behavior

1. Kubernetes Namespace is not being created

### Desired behavior

1. Kubernetes Namespace should be created

### Workaround

_No response_

### rad Version

edge

### Operating system

_No response_

### Additional context

_No response_

### Would you like to support us?

- [ ] Yes, I would like to support you

[AB#14435](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/14435)

### PR DESCRIPTION
**Pull request by vishwahiremat**
- Environment name is only created when env is created using `rad env create` command and when created using bicep. So added changes to move namespace creation logic to server side.
- Added functional tests to validate the `existing` keyword with portable resources.

# Description

_Please explain the changes you've made._

## Type of change

- This pull request fixes a bug in Radius and has an approved issue (issue link required).
- This pull request adds or changes features of Radius and has an approved issue (issue link required).
- This pull request is a minor refactor, code cleanup, test improvement, or other maintenance task and doesn't change the functionality of Radius (issue link optional).

Fixes: #8464 

## Contributor checklist
Please verify that the PR meets the following requirements, where applicable:

- An overview of proposed schema changes is included in a linked GitHub issue.
    - [ ] Yes
    - [ ] Not applicable
- A design document PR is created in the [design-notes repository](https://github.com/radius-project/design-notes/), if new APIs are being introduced.
    - [ ] Yes
    - [ ] Not applicable
- The design document has been reviewed and approved by Radius maintainers/approvers.
    - [ ] Yes
    - [ ] Not applicable
- A PR for the [samples repository](https://github.com/radius-project/samples) is created, if existing samples are affected by the changes in this PR.
    - [ ] Yes
    - [ ] Not applicable
- A PR for the [documentation repository](https://github.com/radius-project/docs) is created, if the changes in this PR affect the documentation or any user facing updates are made.
    - [ ] Yes
    - [ ] Not applicable
- A PR for the [recipes repository](https://github.com/radius-project/recipes) is created, if existing recipes are affected by the changes in this PR.
    - [ ] Yes
    - [ ] Not applicable

### CODE REVIEW

**Comment by ytimocin** [comment]
Have you checked this [issue](https://github.com/radius-project/radius/issues/8464) @vishwahiremat? I was running into an issue where namespace wasn't being created during `rad deploy env.bicep`.

File: test/functional-portable/datastoresrp/noncloud/resources/mongodb_test.go [hunk 1]
```diff
@@ -114,3 +114,58 @@ func Test_MongoDB_Recipe(t *testing.T) {
 
 	test.Test(t)
 }
+
+func Test_MongoDB_Recipe_Existing(t *testing.T) {
+	envTemplate := "testdata/datastoresrp-resources-mongodb-recipe-and-env.bicep"
+	existingTemplate := "testdata/datastoresrp-resources-mongodb-recipe-exsiting.bicep"
```
Comment (ytimocin) [inline test/functional-portable/datastoresrp/noncloud/resources/mongodb_test.go:120]:
```suggestion
	existingTemplate := "testdata/datastoresrp-resources-mongodb-recipe-existing.bicep"
```

File: test/functional-portable/datastoresrp/noncloud/resources/mongodb_test.go [hunk 2]
```diff
@@ -114,3 +114,58 @@ func Test_MongoDB_Recipe(t *testing.T) {
 
 	test.Test(t)
 }
+
+func Test_MongoDB_Recipe_Existing(t *testing.T) {
```
Comment (ytimocin) [inline test/functional-portable/datastoresrp/noncloud/resources/mongodb_test.go:118]: Where do we test that the namespace exists? Can we also use a better (more specific) naming for the test?

File: test/functional-portable/datastoresrp/noncloud/resources/testdata/datastoresrp-resources-mongodb-recipe-exsiting.bicep
Comment (ytimocin) [inline test/functional-portable/datastoresrp/noncloud/resources/testdata/datastoresrp-resources-mongodb-recipe-exsiting.bicep:1]: Name needs to be changed.

File: pkg/corerp/frontend/controller/environments/createorupdateenvironment_test.go
Comment (ytimocin) [inline pkg/corerp/frontend/controller/environments/createorupdateenvironment_test.go:1]: Where did we add the namespace check to the tests?

**Review by ytimocin — CHANGES_REQUESTED** [review]
We need to add namespace check to functional and unit tests. Bicep file name also needs to be changed.

File: test/functional-portable/datastoresrp/noncloud/resources/testdata/datastoresrp-resources-mongodb-recipe-exsiting.bicep
Comment (vishwahiremat) [reply test/functional-portable/datastoresrp/noncloud/resources/testdata/datastoresrp-resources-mongodb-recipe-exsiting.bicep:1]: updated the name

File: pkg/corerp/frontend/controller/environments/createorupdateenvironment_test.go
Comment (vishwahiremat) [reply pkg/corerp/frontend/controller/environments/createorupdateenvironment_test.go:1]: added the check for namespace in the unit tests

File: test/functional-portable/datastoresrp/noncloud/resources/mongodb_test.go [hunk 3]
```diff
@@ -114,3 +117,61 @@ func Test_MongoDB_Recipe(t *testing.T) {
...
+			K8sObjects: &validation.K8sObjectSet{
+				Namespaces: map[string][]validation.K8sObject{
+					appNamespace: {
+						validation.NewK8sPodForResource(name, "mongo-ctnr-exst").ValidateLabels(false),
+					},
+				},
+			},
+			PostStepVerify: func(ctx context.Context, t *testing.T, ct rp.RPTest) {
+				_, err := ct.Options.K8sClient.CoreV1().Namespaces().Get(context.Background(), name, metav1.GetOptions{})
+				require.NoError(t, err)
```
Comment (ytimocin) [inline test/functional-portable/datastoresrp/noncloud/resources/mongodb_test.go:172]: Would this throw a NotFound Exception if the namespace doesn't exist?

**Review by ytimocin — DISMISSED** [review]

File: test/functional-portable/datastoresrp/noncloud/resources/mongodb_test.go (hunk 3 above)
Comment (vishwahiremat) [reply test/functional-portable/datastoresrp/noncloud/resources/mongodb_test.go:172]: yes thats correct,

File: pkg/corerp/frontend/controller/environments/createorupdateenvironment_test.go
Comment (kachawla) [inline pkg/corerp/frontend/controller/environments/createorupdateenvironment_test.go:1]: can we add a unit test for already existing namespace? https://github.com/radius-project/radius/blob/b5d1af3577f7d5c6c2bd79ed37b6459b4c99a8d5/pkg/corerp/frontend/controller/environments/createorupdateenvironment.go#L100

Let me know if it's covered and I missed it.

File: test/functional-portable/datastoresrp/noncloud/resources/mongodb_test.go [hunk 4]
```diff
@@ -114,3 +117,61 @@ func Test_MongoDB_Recipe(t *testing.T) {
...
+	existingTemplate := "testdata/datastoresrp-resources-mongodb-existing-env-scoped-resource.bicep"
+	name := "dsrp-resources-mongodb-recipe-and-env"
+	appNamespace := "dsrp-resources-mongodb-recipe-existing-app"
+	test := rp.NewRPTest(t, name, []rp.TestStep{
+		{
+			Executor: step.NewDeployExecutor(envTemplate, testutil.GetBicepRecipeRegistry(), testutil.GetBicepRecipeVersion()),
+			RPResources: &validation.RPResourceSet{
+				Resources: []validation.RPResource{
+					{
+						Name: "dsrp-resources-mongodb-recipe-and-env",
```
Comment (kachawla) [inline test/functional-portable/datastoresrp/noncloud/resources/mongodb_test.go:132]:
```suggestion
						Name: name,
```

File: test/functional-portable/datastoresrp/noncloud/resources/mongodb_test.go [hunk 5]
```diff
@@ -114,3 +117,61 @@ func Test_MongoDB_Recipe(t *testing.T) {
...
+				},
+			},
+			SkipObjectValidation: true,
+		},
+		{
+			Executor: step.NewDeployExecutor(existingTemplate, testutil.GetMagpieImage()),
+			RPResources: &validation.RPResourceSet{
+				Resources: []validation.RPResource{
+					{
+						Name: "dsrp-resources-mongodb-recipe-existing",
```
Comment (kachawla) [inline test/functional-portable/datastoresrp/noncloud/resources/mongodb_test.go:148]: can you please move this name strings into variables since they are repeated?

File: test/functional-portable/datastoresrp/noncloud/resources/mongodb_test.go [hunk 6]
```diff
@@ -114,3 +117,61 @@ func Test_MongoDB_Recipe(t *testing.T) {
...
+						Name: "dsrp-resources-mongodb-recipe-and-env",
+						Type: validation.EnvironmentsResource,
+					},
+					{
+						Name: "mongodb-db-existing",
+						Type: validation.MongoDatabasesResource,
+					},
+				},
+			},
+			SkipObjectValidation: true,
```
Comment (kachawla) [inline test/functional-portable/datastoresrp/noncloud/resources/mongodb_test.go:141]: what's the benefit of skipping object validation for this test?

File: test/functional-portable/datastoresrp/noncloud/resources/testdata/datastoresrp-resources-mongodb-recipe-and-env.bicep [hunk 7]
```diff
@@ -0,0 +1,37 @@
...
+  location: 'global'
+  properties: {
+    compute: {
+      kind: 'kubernetes'
+      resourceId: 'self'
+      namespace: 'dsrp-resources-mongodb-recipe-and-env'
+    }
+    recipes: {
+      'Applications.Datastores/mongoDatabases': {
+        mongoazure: {
```
Comment (kachawla) [inline test/functional-portable/datastoresrp/noncloud/resources/testdata/datastoresrp-resources-mongodb-recipe-and-env.bicep:18]: the recipe is provisioning mongo on kubernetes, should the name be updated to not include azure?

File: test/functional-portable/datastoresrp/noncloud/resources/mongodb_test.go [hunk 8]
```diff
@@ -114,3 +117,61 @@ func Test_MongoDB_Recipe(t *testing.T) {
 
 	test.Test(t)
 }
+
+func Test_MongoDB_EnvScoped_ExistingResource(t *testing.T) {
```
Comment (kachawla) [inline test/functional-portable/datastoresrp/noncloud/resources/mongodb_test.go:121]: can you please add an overall comment about what this test is for/what it does etc?

File: pkg/corerp/frontend/controller/environments/createorupdateenvironment_test.go
Comment (vishwahiremat) [reply pkg/corerp/frontend/controller/environments/createorupdateenvironment_test.go:1]: added a test for this.

File: pkg/corerp/frontend/controller/environments/createorupdateenvironment.go [hunk 9]
```diff
@@ -89,6 +95,16 @@ func (e *CreateOrUpdateEnvironment) Run(ctx context.Context, w http.ResponseWrit
 		}
 	}
 
+	// Create environment namespace if it doesn't exist.
+	err = e.Options().KubeClient.Create(ctx, &corev1.Namespace{ObjectMeta: metav1.ObjectMeta{Name: namespace}})
+	if apierrors.IsAlreadyExists(err) {
+		logger.Info("Using existing namespace", "namespace", namespace)
+	} else if err != nil {
+		return nil, err
```
[the remark this answers is not in the document]
Comment (vishwahiremat) [reply pkg/corerp/frontend/controller/environments/createorupdateenvironment.go]: updated it

File: test/functional-portable/datastoresrp/noncloud/resources/mongodb_test.go (hunk 5 above)
Comment (vishwahiremat) [reply test/functional-portable/datastoresrp/noncloud/resources/mongodb_test.go]: updated it

File: test/functional-portable/datastoresrp/noncloud/resources/mongodb_test.go (hunk 6 above)
Comment (vishwahiremat) [reply test/functional-portable/datastoresrp/noncloud/resources/mongodb_test.go:142]: i was trying to mimic the existing test `Test_MongoDB_Recipe` since we only add the validation for the container resource here, i added the same in the next test step.

File: test/functional-portable/datastoresrp/noncloud/resources/testdata/datastoresrp-resources-mongodb-recipe-and-env.bicep (hunk 7 above)
Comment (vishwahiremat) [reply test/functional-portable/datastoresrp/noncloud/resources/testdata/datastoresrp-resources-mongodb-recipe-and-env.bicep]: updated it

File: test/functional-portable/datastoresrp/noncloud/resources/mongodb_test.go (hunk 8 above)
Comment (vishwahiremat) [reply test/functional-portable/datastoresrp/noncloud/resources/mongodb_test.go:125]: done

File: test/functional-portable/datastoresrp/noncloud/resources/mongodb_test.go [hunk 10]
```diff
@@ -114,3 +117,66 @@ func Test_MongoDB_Recipe(t *testing.T) {
 
 	test.Test(t)
 }
+
+// This test verifies deployment of shared environment scoped resource using 'existing' keyword.
+// It has 2 steps:
+// 1. Deploy the environment and mongodb resource to the environment namespace.
+// 2. Deploy and app that uses the existing mongodb resource using the 'existing' keyword.
```
Comment (kachawla) [inline test/functional-portable/datastoresrp/noncloud/resources/mongodb_test.go:124]:
```suggestion
// 2. Deploy an app that uses the existing mongodb resource using the 'existing' keyword.
```

**Review by kachawla — DISMISSED** [review]

File: test/functional-portable/dynamicrp/noncloud/resources/dynamicrp_test.go [hunk 11]
```diff
@@ -101,3 +102,85 @@ func Test_DynamicRP_Recipe(t *testing.T) {
 
 	test.Test(t)
 }
+
+// This test verifies deployment of shared environment scoped resource using 'existing' keyword.
+// It has 2 steps:
+// 1. Deploy the environment and postgres resource to the environment namespace.
+// 2. Deploy an app that uses the existing postgres resource using the 'existing' keyword.
+func Test_Postgres_EnvScoped_ExistingResource(t *testing.T) {
```
Comment (kachawla) [inline test/functional-portable/dynamicrp/noncloud/resources/dynamicrp_test.go:110]: Do we need still need to keep the old test above? The first two test steps are same for [Test_DynamicRP_Recipe](https://github.com/radius-project/radius/blob/849f910ed47a5dad0adbdee0a46856407e513f64/test/functional-portable/dynamicrp/noncloud/resources/dynamicrp_test.go#L45) test, except the application which I don't know is adding any value. So I wonder if we should remove that.

File: test/functional-portable/dynamicrp/noncloud/resources/dynamicrp_test.go [hunk 12]
```diff
@@ -101,3 +102,85 @@ func Test_DynamicRP_Recipe(t *testing.T) {
...
+						validation.NewK8sPodForResource(name, "postgres-cntr").ValidateLabels(false),
+					},
+				},
+			},
+			PostStepVerify: func(ctx context.Context, t *testing.T, ct rp.RPTest) {
+				_, err := ct.Options.K8sClient.CoreV1().Namespaces().Get(context.Background(), name, metav1.GetOptions{})
+				require.NoError(t, err)
+			},
+		},
+	})
```
Comment (kachawla) [inline test/functional-portable/dynamicrp/noncloud/resources/dynamicrp_test.go:184]: What is this step verifying?

File: test/functional-portable/dynamicrp/noncloud/resources/dynamicrp_test.go [hunk 13]
```diff
@@ -101,3 +102,85 @@ func Test_DynamicRP_Recipe(t *testing.T) {
...
+						Name: name,
+						Type: validation.EnvironmentsResource,
+					},
+					{
+						Name: "existing-postgres",
+						Type: "test.resources/postgres",
+					},
+				},
+			},
+			SkipObjectValidation: true,
```
Comment (kachawla) [inline test/functional-portable/dynamicrp/noncloud/resources/dynamicrp_test.go:150]: Why are we skipping this?

File: test/functional-portable/dynamicrp/noncloud/resources/dynamicrp_test.go (hunk 12 above)
Comment (vishwahiremat) [reply test/functional-portable/dynamicrp/noncloud/resources/dynamicrp_test.go:184]: its is verifying that the test creates a environment namespace.

File: test/functional-portable/dynamicrp/noncloud/resources/dynamicrp_test.go (hunk 11 above)
Comment (vishwahiremat) [reply test/functional-portable/dynamicrp/noncloud/resources/dynamicrp_test.go:110]: i agree we could remove that, but also the test added in this PR is about deploying resource to the env namespace and using existing keyword right, so i was thinking its okay to have a separate one for testing dynamic rp recipe? maybe we could replace this test with e2e test we may add for upcoming udt features if thats okay.

File: test/functional-portable/dynamicrp/noncloud/resources/dynamicrp_test.go (hunk 13 above)
Comment (vishwahiremat) [reply test/functional-portable/dynamicrp/noncloud/resources/dynamicrp_test.go:150]: I copied the test from the mongodb recipe test, where we skip this.

File: test/functional-portable/dynamicrp/noncloud/resources/dynamicrp_test.go (hunk 11 above)
Comment (kachawla) [reply test/functional-portable/dynamicrp/noncloud/resources/dynamicrp_test.go:110]: That sounds good. To make sure I understand - the main difference you are calling out is that the UDT resource is getting deployed in the env namespace instead of app namespace, right?

File: test/functional-portable/dynamicrp/noncloud/resources/dynamicrp_test.go (hunk 12 above)
Comment (kachawla) [reply test/functional-portable/dynamicrp/noncloud/resources/dynamicrp_test.go:184]: Ah to validate server side creation of env namespace? Can you add a comment here in the code for others to know why this verification is needed.

File: test/functional-portable/dynamicrp/noncloud/resources/dynamicrp_test.go (hunk 13 above)
Comment (kachawla) [reply test/functional-portable/dynamicrp/noncloud/resources/dynamicrp_test.go:150]: Do you know why it was skipped in the mongodb recipe test?

File: test/functional-portable/dynamicrp/noncloud/resources/dynamicrp_test.go (hunk 12 above)
Comment (vishwahiremat) [reply test/functional-portable/dynamicrp/noncloud/resources/dynamicrp_test.go]: yes thats correct, added a comment

File: test/functional-portable/dynamicrp/noncloud/resources/dynamicrp_test.go (hunk 13 above)
Comment (vishwahiremat) [reply test/functional-portable/dynamicrp/noncloud/resources/dynamicrp_test.go]: dont remember why it was skipped, but anyways i added validation for this test.

File: test/functional-portable/dynamicrp/noncloud/resources/dynamicrp_test.go [hunk 14]
```diff
@@ -101,3 +102,92 @@ func Test_DynamicRP_Recipe(t *testing.T) {
...
+					},
+					{
+						Name: "existing-postgres",
+						Type: "test.resources/postgres",
+					},
+				},
+			},
+			K8sObjects: &validation.K8sObjectSet{
+				Namespaces: map[string][]validation.K8sObject{
+					appNamespace: {
```
Comment (kachawla) [inline test/functional-portable/dynamicrp/noncloud/resources/dynamicrp_test.go:152]: Should this be env namespace?

File: test/functional-portable/dynamicrp/noncloud/resources/testdata/usertypealpha.yaml
Comment (kachawla) [inline test/functional-portable/dynamicrp/noncloud/resources/testdata/usertypealpha.yaml:1]: Should this file be renamed now that it contains more than just usertypealpha resource type?

Comment (vishwahiremat) [reply test/functional-portable/dynamicrp/noncloud/resources/testdata/usertypealpha.yaml:1]: as discussed offline, will do it as part of a different PR as it includes workflow changes

File: test/functional-portable/dynamicrp/noncloud/resources/dynamicrp_test.go (hunk 14 above)
Comment (vishwahiremat) [reply test/functional-portable/dynamicrp/noncloud/resources/dynamicrp_test.go]: good catch! updated it to use env namespace

**Review by kachawla — APPROVED** [review]
